### ISSUE TITLE
Slighty wrong colors

### ISSUE THREAD

**Issue by antimatter84** [ManiacalLabs/BiblioPixel#10]
Hello,
I have a LED strip with the LPD8806 driver. Using BiblioPixel, some colors don't look right.

For example: yellow (255,255,0) from the colors module looks quite green. I have to fill the LED strip with (255,148,0), so I can say: yes, this is yellow for me. I could raise the green part to 156, but anything higher looks too greenish.

Another example is this: setting the color to white (255,255,255) looks slightly blue. Something like (255,214,138) looks more like a white. I have to reduce the green part, because otherwise it would look slightly green.

And I noticed, that any of the individual LED components (red, green, blue) will only be lit at a value of 28 or above. Any value below is like an off state.

What is the source of these effects? Is it normal for the strip/controller itself? 
Is there a way to do some color corrections, so when setting White from the colors module, I actually will see the white I expect?

**Comment by frruit** [comment]
Hi,
i have also the same issue. The colors yellow and orange are not really presentable by the LPD8806. I think it's not the problem of the software. Here you can play with a color mapping solution but it's really hard to find out the values that will be nearly the colors that you expect. Maybe someone has good values for this case. I would be glad to get some better then mine.

Currently i think about buying a strip with the WS2801 or maybe another type. Maybe someone has a good suggestion what strip types are well to get all colors that are presented correctly.

**Comment by adammhaile** [comment]
Hey @antimatter84 - The LPD8806 strips are not great color-wise without some color correction. However, the DriverLPD8806 class already does do gamma correction since they always need it. Maybe your strip is already gamma corrected??  That would be a new one. Try this:

```python
driver = DriverLPD8806(num)
driver.gamma = [i for i in range(256)]
```

Maybe my decision to ALWAYS force gamma correction for the LPD8806 was a bad idea... it's always needed it. The symptoms you mention actually sound like it's OVER gamma corrected. 

Where did you buy your strips?

I'd love to know if this works for you and any other details you have. My testing is limited by my sizable, yet still limited, collection of LED hardware. Can't test for every manufacturer.

Let me know.

**Comment by adammhaile** [comment]
@frruit - In my experience, WS2801 and WS2812 generally don't really need gamma correction... at least not much. Try the solution I gave to @antimatter84, which basically disables the color correction. Maybe I just need to not force it, which is an easy enough change.

**Comment by antimatter84** [comment]
Hi Adam,
I tried the simple range(256) for the gamma correction. But this way, the strip goes crazy. Only the first LED is lit blue in different intensities, no matter what RGB combinations I try.

I bought the LED strip together with a co-worker at ebay. It was probably this one:
http://www.ebay.de/itm/5m-LED-Strip-48-LEDs-m-24-ICs-LPD8806-5V-RGB-IP67-Wasserdicht-Silikon-Schlauch-/201225233482?nma=true&si=tGIx%252FxZiOUDDYN1YIq8LFKCnv%252Bs%253D&orig_cvip=true&rt=nc&_trksid=p2047675.l2557

I wrote a small GUI with RGB sliders around the DriverNetwork example to easily experiment with the colors. This may be useful to others. http://pastebin.com/fWR4jMPi

**Comment by adammhaile** [comment]
try setting SPISpeed = 2. Might be some interference.

**Comment by antimatter84** [comment]
SPISpeed=2 doesn't help. Crazyness only slightly reduced by 1% :-)

**Comment by adammhaile** [comment]
Weird.... really can't say I'm sure what it is then. Can you share some code. Maybe a video?

**Comment by adammhaile** [comment]
Any luck? Or should I close this?

**Comment by antimatter84** [comment]
Sorry for the delay, I was on a business trip. I will see, if I can put together some pictures.

**Comment by adammhaile** [comment]
thanks!

**Comment by adammhaile** [comment]
Any chance to take those pictures?

**Comment by antimatter84** [comment]
Right, here are the pictures. The color may be not exactly correct on each monitor. The pictures were only cropped and scaled down. No color corrections. Below the LED strip is a sheet of white paper.

This should be yellow, but is more green than yellow. RGB=255,255,0
![255-255-0](https://cloud.githubusercontent.com/assets/10585451/5994352/dfa49a54-aa6f-11e4-8dcc-42d3f70fff50.jpg)

This looks like an real yellow. RGB=255,160,0
![255-160-0](https://cloud.githubusercontent.com/assets/10585451/5994350/df9cc1c6-aa6f-11e4-88db-6e243080ef85.jpg)

This should be white as in RGB=255,255,255, but has some noticable blue in it. The picture might show a bit too much blue, at least on my monitor. With eyeball Mk 1, it looks like a cyan blue to me.
![255-255-255](https://cloud.githubusercontent.com/assets/10585451/5994353/dfa66884-aa6f-11e4-9b55-fce73574ca4a.jpg)

This looks like a real white at RGB=255,214,138
![255-214-138](https://cloud.githubusercontent.com/assets/10585451/5994351/df9e4cda-aa6f-11e4-97b9-8be1b59670a3.jpg)

**Comment by adammhaile** [comment]
You're green and blue are way to high... is this with the gamma disable hack I sent you or without (meaning that gamma is applied)? If you try using [FastLED](http://fastled.io) on an Arduino (if you have one) does it do the same thing? I bet it will...

**Comment by antimatter84** [comment]
This pictures are taken with the default gamma corrections, as they are programmed into the LPD8806 class. With the gamma disable hack the strip goes completely crazy, e.g. only 1st LED is blue, rest is red/pink and raising the red part will only change the intensity of the blue LED.

Sorry, I don't have an Arduino.

**Comment by adammhaile** [comment]
Oh wait... LPD8806. Duh. That's some special gamma, sorry. 
Try this instead:

```python
driver = DriverLPD8806(num)
driver.gamma = [i/2 for i in range(256)]
```

**Comment by antimatter84** [comment]
Will try that and get back to you after some sleep. It's past midnight in my timezone. ;-)

**Comment by adammhaile** [comment]
Cool. Sounds good.

**Comment by adammhaile** [comment]
Any luck?

**Comment by antimatter84** [comment]
Just tried your proposed gamma correction. Sorry, but the result is somewhat... like you put cocoa powder in your coffeemaker and expect a cup of hot chocolat, but you end up with fried fish in strawberry sauce.

Forgive me this extreme comparison. The effects are really hard to describe. it's quite similar to the previous description:

>Raising the red part will only change the intensity of the blue LED, e.g. max at R=0, off at R=1, increasing to max at R=16(?), off again at R=17, and so on...

When modifying all the RGB components, the rest of the LEDs will change their color in a rather random fashion and won't resemble anything close to the RGB values.

I believe, we must not omit the 0x80 as the strip needs the most significant bit always to be 1. I read it somewhere. Applying this to your proposed gamma correction didn't help either.

I made a custom "gamma correction" for each channel:
```
r = self.red_slider.value()
g = self.green_slider.value()
b = self.blue_slider.value()

# correction factors
r *= 1.0
g *= 0.63
b *= 0.545

if b > 0:
  g += b * 0.4
  if g > 255:
    g = 255

t = (int(r), int(g), int(b))
self.led.fill(t)
self.led.update()
```
This algorithm along with the builtin gamma correction produces the expected colors pretty good. It isn't perfect yet. Moving the blue slider will always raise the green part a bit... but it's a start.

**Comment by adammhaile** [comment]
Very weird... I've been using LPD8806 strips for along time and never had
so much color trouble.
However, the MSB must NOT be set high. It's the latch bit... that's why it
went haywire with my first gamma hack. Seeing that bit high tells the ICs
to latch and set the colors. That's why the LPD is 7-bit per channel color.

I like your correction factor method though... I'll look into a way of
adding the ability to do something similar.
