### ISSUE TITLE
Fix, remove or document workaround for the FILE interface to SPI

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#1024]
@flickerfly

From this thread.  https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/maniacal-labs-users/5TV-tDGS6tk/XVMMkNGyCQAJ

Can we just require periphery and be done with it?
Is the issue general to SPI or just to some specific configurations?

Just want your weigh-in, Adam, and then I can remove you from the bug.  :-)

**Comment by adammhaile** [comment]
@rec - The reason for FILE being default is ease of use over performance.
I'm not actually seeing a problem with it on my end though. So I feel like
this is just specific to something with that one setup. Unless we start
seeing others with the same problem I don't see a reason to change anything.
