### ISSUE TITLE
POV is broken in multiple ways

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#1025]
It's because the Field that's everywhere else called `height` is called `povHeight` in this Layout.

**Comment by rec** [comment]
The reason for the conflict is simple - there are two different "heights".  There's the height of the virtual display, and there's the height of the actual display, which is 1.

But we need to standardize on "height means height of the display we draw on, not the output display".

**Comment by rec** [comment]
ARG - also the order of the parameters in POV is reversed!

They come in `height, width` and then they are passed on `width, height`.  I'll fix that too - and yes, it'll be backwards compatible.

**Comment by adammhaile** [comment]
POV has not really been touched in forever. I have no issues with breaking
the API to make it work with newer stuff.
