### ISSUE TITLE
Animations inside collections run more slowly

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#1042]
The code sleeps both for the container class, and the class that is contained in it.

**Comment by rec** [comment]
Worse than that - it also calls "push_to_driver" on each subanimation!  :-o

**Comment by rec** [comment]
Just pinging you, @adammhaile, to alert you to this!

This has always been there in the code.  I just can't believe neither of us never saw this.  :-O :-D

**Comment by adammhaile** [comment]
oh god.... that's terrible :(

**Comment by rec** [comment]
Well, the good part is that I saw it before anyone else!  :-D

**Comment by rec** [comment]
After some analysis, there will have to be some changes to behavior to make this work.

What happens if we have the following Project:

    run: {fps: 12}

    animation: 
      typename: .sequence
      run: {fps: 23}
      animations:
          - typename: $bpa.matrix.bloom
             run: {fps: 29}

What is the `fps` then?  :-o

But we are currently using "fps" as our way of speeding up and slowing down animations (which is really horrid if you think about - we should think of fps as a _rendering_ choice!)

So I can't just junk `fps` inside animations - which would be the easy way to fix this, just ignore all the timing information inside nested animations.

Developing!

So glad I caught this before 3.5.  :-D

**Comment by rec** [comment]
OK, let me write up a plan while I'm on this page.  :-D

Basically, we have two goals

* animations which have different fps's for subanimations to continue to work
* we want the actual sleep and push_to_driver to occur only at the top level

--- lots of concentrated thought ---

OK, so I have a plan that preserves those and is actually pretty clear.  

Summary:  

1. We're going to continue to use the framerate as an informal clock speed multiplier

2. I might or might not create a new class for the top level animation only that just runs its animation cycles - so inner animations won't even have access to "sleep" and "push to driver".

3. The fps will be taken from the "lowest possible animation" - another way to say this is that any animation's fps overrides its containing classes fps.

4. It is an error to set fps in a subanimation of a Parallel animation - because multiple animations can be playing at once.

That last one is a little restrictive, but what can you do?  It's the flaw in the whole "fps == animation speed" idea. I don't see any backwards compatible way to do this.

----

Note that this all stemmed from my "POV" research, so that did quite a bit of good for the codebase.
