### ISSUE TITLE
Long parameter lists and parameter forwarding.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#106]
We have this issue in several of our constructors and in some other methods like `BaseAnimation.run`.

Take our drivers.  Their constructors take a lot of parameters, which they immediately pass unchanged to the parent class.  We could use `**kwds` - except we'd then lose the documentation of the parameters that were legal.

It's a constant drag on the eye when reading, and important information (like default values that are overridden) are hidden.

If everything were always created through `Projects`, this would mitigate that issue.

I have to believe that a lot of other people's projects have this issue too.

I wonder what a good way to do this is...

**Comment by adammhaile** [comment]
Yeah... struggled with the best way to do this for a long time. One reason I haven't changed it is that when you just do kwargs most auto code completion tools (like the one I use in Atom) can't give you any hint of what the parameters are. That's kind of a dealbreaker for me.
However, I wonder if those tools could parse the docstring to give you the same info. At the very least I know that atom will *show* the docstring which would have all the info we need. I think some testing is in order... still have to look at all that docstring stuff anyways.

**Comment by rec** [comment]
Even though I don't use automatic completion of parameters, I completely understood this from before, and that's the main reason I haven't touched this.

Generally, the autogenerated Python help is pretty bad.  Very often you don't even get the constructor at all because people are using some sort of trick or other.

As you say, I feel there should be some way to automate past this but I haven't even formulated a clear search query...

**Comment by rec** [comment]
https://stackoverflow.com/questions/42471083/perfect-forwarding-in-python

**Comment by rec** [comment]
This new solution just appeared on SO:  http://stackoverflow.com/a/42595580/43839

Reading now...

**Comment by rec** [comment]
Moving this to 4.0.  No really good solution has presented itself.

**Comment by rec** [comment]
Even though I moved this to 4.0, I now think I do have a solution, and it uses `attrs` though not as a critical part.

It's back to a separate `Desc` class.

You pass in a `Desc` calls to the constructor - not the separate values.

We have a default `Desc` for the derived classes!  And that's how the "overriding attributes" idea works.

I'll sketch out a change, with attrs.

**Comment by rec** [comment]
"Projects" basically handles this...
