### ISSUE TITLE
Workflow for using Projects from the Python command line

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#1066]
If you want to fire up a command line and experiment with Projects, how do you do it?

The code is all there to do it, it wouldn't even be that hard - if I documented it.

**Comment by rec** [comment]
@adammhaile 

I'm beginning to wonder if the whole Project thing wasn't a negative for most users.  Perhaps all people wanted to do was write little programs to get simple lighting things done and get a sense of achievement.

Projects and all that comes with it give you far more power and the ability to do much more sophisticated things, but perhaps that's not what people actually want - that they mostly want something that flashes and they point to it and say, "I wrote that program".

That's sorta :-/ to contemplate but it gives me some hint as to how to make it more appealing to people.

From marketing - you know those powdered cake mixes they sell to "make at home" where you break an egg into the batter and mix it in?  Well, of course, they could just as easily put the egg into the mix and get exactly the same effect - they do this because it gives the consumer the feeling that they are "actually cooking".

So I think that this issue needs to also handle "doing it from a simple program".

I know that I _have_ preserved the ability to run old programs from the command line, because the one release that broke it got immediate responses!

But you can't use any of the excitement of Projects that way.

---

I need to think about this some more.  It's somewhat daunting...

**Comment by rec** [comment]
Ah, sorry for the spam, I like to work things out on paper.

Let me write out possible workflow and see how it flows.

    pb = ProjectBuilder()
    pb.animation = MyAnimation()
    pb.shape = 32

    pb.construct()  # gives errors
    pb.clear()
    pb.start()      # starts in the background by default
    pb.open_simpixel()
    pb.stop()
    pb.restart()
    pb.save('filename.yml')
    pb.fill()       # fills in missing parts without constructing 
        
Really not so bad...

**Comment by adammhaile** [comment]
Will respond later... Holiday here in the states :)

**Comment by rec** [comment]
Hah, I forgot entirely!  :-D

**Comment by rec** [comment]
I did this!  Super fun.
