### ISSUE TITLE
Width and height are wrong in animations with multiple devices.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#1082]
In the below project, the animation's automatically comuted width and height should be 128 x 96 but is 128 x 32

    driver:
      typename: .serial.driver.TeensySmartMatrix
      width: 128
      height: 32

    drivers:
      - device_id: 10
      - device_id: 11
      - device_id: 12

    layout:
        typename: matrix
        width: 128
        gen_coord_map:
            - {dx: 32, dy: 32}
            - {dx: 32, dy: 32}
            - {dx: 32, dy: 32}

Workaround - explicitly specify width and height in the animation.

**Comment by adammhaile** [comment]
If that is broken it's recent. That has always worked fine for multidriver

**Comment by adammhaile** [comment]
I stand corrected, it's supposed to error out if you don't pass it a
coord_map when using multi-driver:
https://github.com/ManiacalLabs/BiblioPixel/blob/dev/bibliopixel/layout/matrix.py#L71-L88
Which you did... but it's wrong. You have a 128x96 display but are passing
it three 32x32 shapes for the coord map.

**Comment by rec** [comment]
Aha, what should I be passing it?

**Comment by rec** [comment]
ah, the dx should be 128?  but why is it "d"x then?

**Comment by adammhaile** [comment]
Yep... Why would dx be 32??? Your driver is driving a 128x32 panel, so of
course the X component of the coord_map shape should be 128.

**Comment by rec** [comment]
So why is it "d"x, then?  :-D

I have a lovely light going, so I'm closing this one!

**Comment by rec** [comment]
We need to document this thoroughly but all in good time.
