### ISSUE TITLE
Fancy out-of-the-box SimPixel demo in BP.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#111]
There needs to be a script that is installed with bp that "does something fun instantly" and then "does a bunch of fun things if you type a bit more".

Basically, if people play with anything for two minutes, your chances of hooking them as a user goes way, way up.

Even just ONE thing that makes a fancy demo with zero sweat is huge.

**Comment by rec** [comment]
Hint - the last line of the code will be `webbrowser.open('http://simpixel.io').  :-)

**Comment by adammhaile** [comment]
+1000 to this. Will prob leave the "project" side of things up to you, but I'll get the auto simpixel launching going.

**Comment by rec** [comment]
This is done though I expect to add more demos to this.
