### ISSUE TITLE
dotfiles or other way for users to store defaults.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#112]
My theory about people's usage patterns is that they will nearly always do a lot of work in a row with exactly the same hardware setup which never changes.

We want to make this most-common workflow as easy as possible.

We should store this information and other such in a `.bibliopixel` file or a `.bibliopixel/` subdirectory in the user's home directory.

**Comment by adammhaile** [comment]
Agree with this however it should run a default config if nothing passed but we should allow a config name to be passed "bibliopixel --config XMasTree" for example. I would use the &%!# out of this. And we should always assume that people would have multiple configs on one machine.

**Comment by rec** [comment]
Got it.

I'm bringing in:

List and change the .bibliopixel settings from #113, which I'm closing.

**Comment by rec** [comment]
OK!  Let me write this out to clear my mind.

Right now, the only values we set are used in Projects.

We have four parts: device, led, animation, run

The first three have a `typename` and indeed, the most common case will be having just a typename, so we'll treat a single string as `typename`

**Comment by rec** [comment]
This is almost done.  The last step is actually to read missing parts from your project from the settings...

**Comment by rec** [comment]
Done.
