### ISSUE TITLE
SPI SM16716 Support

### ISSUE THREAD

**Issue by getty23** [ManiacalLabs/BiblioPixel#1140]
Hi, 

I was wondering if SPI support for SM16716 is already in place or planned. When I check the code SPI/driver.py I just see support for APA102, LPD8806, WS281X, WS2801. But when I check the documentation (https://maniacallabs.github.io/BiblioPixel/tutorial/drivers/the-spi-driver.html) it looks like that SM16716 is supported (but this might be wrong or I interpreted the documentation in the wrong way).
We are looking for a direct SM16716 SPI integration and it would be great if you could clarify on this point a bit. 

Thanks a lot and best regards,
Florian

**Comment by adammhaile** [comment]
You found a copy/paste error in the docs. The list given there was for the AllPixel which does support SM16716. There is no direct SPI support (via a Raspberry Pi I assume you want) for SM16716 in BiblioPixel. I'll fix the docs.
The [AllPixel](https://www.tindie.com/products/ManiacalLabs/allpixelmini-universal-led-controller/) is a USB Serial device that BiblioPixel can talk to which understands a ton of different protocols. So in terms of using BiblioPixel, that would be your only option. There is no plan to support SM16717 directly via SPI.

**Comment by getty23** [comment]
Thanks @adammhaile for your quick reply. Too bad that SM16716 is not yet supported. 
At least from my end I'd like to ask for a feature request for this driver.
Thanks

**Comment by adammhaile** [comment]
I would need some LEDs to test with. We take PRs if you wanna give it a
shot. The drivers are pretty basic, especially since you can just base a
new one on another SPI driver.
