### ISSUE TITLE
Installation docu outdated?

### ISSUE THREAD

**Issue by JulesDoe** [ManiacalLabs/BiblioPixel#1143]
After fresh install like described here:
https://maniacallabs.github.io/BiblioPixel/tutorial/getting-started/installing-bibliopixel.html
the result of the testing (on windows)is:

```
PS C:\Users\x\Documents\LED_Strip\test> bp demo       
Available demos are: bloom, circle, cube, matrix
Randomly selected cube
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python36-32\Scripts\bp", line 16, in <module>
    main.main()
  File "c:\users\x\appdata\local\programs\python\python36-32\lib\site-packages\bibliopixel\main\main.py", line 31, in main
    module.run(args)
  File "c:\users\x\appdata\local\programs\python\python36-32\lib\site-packages\bibliopixel\commands\demo.py", line 71, in run
    animation = make_runnable_animation(demo, args)
  File "c:\users\x\appdata\local\programs\python\python36-32\lib\site-packages\bibliopixel\commands\demo.py", line 47, in make_runnable_animation
    project = project_flags.make_project(args, demo)
  File "c:\users\x\appdata\local\programs\python\python36-32\lib\site-packages\bibliopixel\main\project_flags.py", line 163, in make_project
    return project.project(*descs, root_file=root_file)
  File "c:\users\x\appdata\local\programs\python\python36-32\lib\site-packages\bibliopixel\project\project.py", line 189, in project
    project = construct.construct(**desc)
TypeError: construct() missing 1 required keyword-only argument: 'datatype'
```

**Comment by adammhaile** [comment]
Looks like your stacktrace is missing something at the end, there's no actual exception, so I don't know what's happening.
Likely just something wrong with the demo command, but the rest of it should all work fine... been a while since the last release and no issues. I'll check into the demo command when I'm back at a Windows machine. But the full stacktrace would be helpful.

Also, just FYI, when doing markdown code formatting, if it's multi-line you need to use triple back-ticks above and below, not just one :)

**Comment by JulesDoe** [comment]
*Edit* Oh indeed.. sorry

**Comment by adammhaile** [comment]
Ok, I see it now, but that's really weird. I'm not sure what the issue is and I cannot reproduce it locally.
What does `bp --version` show you?
Also, can you give me the output of `pip freeze` and `python --version`?

**Comment by JulesDoe** [comment]
Thank you for looking into it so fast :)

```
PS C:\Users\x\Documents\LED_Strip\my_lights> bp info
Timestamp:        2019-11-06T15:18:52
Python version:   3.6.4
`bp` path:        C:\Users\x\AppData\Local\Programs\Python\Python36-32\Scripts\bp
Library path:     c:\users\x\appdata\local\programs\python\python36-32\lib\site-packages\bibliopixel

Platform:         Windows
Platform version: 10:10.0.18362:SP0:Multiprocessor Free
Platform release: 10

Dependencies:
    bibliopixel: version 3.4.45, git commit: (none), git tag (none)
    BiblioPixelAnimations: version (none), git commit: (none), git tag (none)
    loady: version 1.7.8, git commit: (none), git tag (none)

```

```
PS C:\Users\x\Documents\LED_Strip\my_lights> pip freeze
beautifulsoup4==4.6.0
BiblioPixel==3.4.45
BiblioPixelAnimations==3.20180123.110953
BiblioPixelTriggers==1.0.1
certifi==2018.1.18
chardet==3.0.4
click==6.7
croniter==0.3.20
Cython==0.29.13
Flask==0.12.2
gitdb2==2.0.3
GitPython==2.1.8
idna==2.6
imageio==2.6.1
itsdangerous==0.24
Jinja2==2.10
loady==1.7.8
MarkupSafe==1.0
numpy==1.14.0
opencv-python==3.4.0.12
Pillow==6.0.0
pyserial==3.4
python-dateutil==2.6.1
PyYAML==3.12
requests==2.18.4
scipy==1.3.1
six==1.11.0
smmap2==2.0.3
urllib3==1.22
Werkzeug==0.14.1
```

```
PS C:\Users\x\Documents\LED_Strip\my_lights> python --version
Python 3.6.4
```

**Comment by adammhaile** [comment]
That all looks fine... I'll see if I can reproduce it on Windows tonight.
In the mean time... you're running an old version of python, I'd update to the latest. And then reinstall bibliopixel. Ideally inside a virtualenv. My main guess is something you already had installed is conflicting... I love python but I run everything inside a virtualenv because it's terrible about conflicts between packages.

**Comment by JulesDoe** [comment]
oh okay .. you actualy mention this in the docs bevor everyhing ... but i was to eager to see something blinky ;)
thy i will try this

**Comment by adammhaile** [comment]
No worries... we prefer it but usually not necessary. Given what you have installed you clearly are used to python... it's people who are already using python for other stuff that usually cause the problems ;)

**Comment by JulesDoe** [comment]
Thank you very moutch :)  I reinstalled in a fresh python 3.8 conda env... and now things work as described :)

**Comment by adammhaile** [comment]
Excellent :) Glad I was right that it was just conflicts
