### ISSUE TITLE
Modify animation and run parameters real-time via potentiometer? 

### ISSUE THREAD

**Issue by VonHirsch** [ManiacalLabs/BiblioPixel#1144]
I'd like to vary animation and/or run parameters based on dials / knobs attached to a matrix.  I see there are various inputs available such as artnet, gamepad, keyboard, midi etc.  Is there any facility for GPIO?

![image](https://user-images.githubusercontent.com/3280180/68908388-1a987f80-0719-11ea-9068-118c0116c77c.png)

p.s. thanks for BiblioPixel, it's insane great

**Comment by adammhaile** [comment]
Sadly no, you'd have to write your own input control. Oddly I think you are the first to ever ask about GPIO... although, I assume you are talking about the Raspberry Pi? That doesn't have analog input... at least not directly, you could of course use an ADC. Personally I'm not a fan of the GPIO on the Pi, it's very high latency. The way I'd do what you want would be to have a simple arduino-type USB serial device read the trimpot and then feed that back over serial.

**Comment by VonHirsch** [comment]
Ok thanks for that, yes exactly right it’s a raspberry pi zero atm.  I’ll see what I can do and submit a PR if something works out.  Good point about analog inputs & latency, for this some delay is acceptable as the interface is primarily for convenience.  In other words the user is more playing with the controls to see what they can do rather than syncing them with a beat or something.  But yea, thanks for the idea about Arduino, I have a few nano’s floating around and that might be just the thing.

**Comment by VonHirsch** [comment]
Well, FWIW I have the arduino speaking midi to the pi as a control for the matrix.  I used midi because it seemed well fitted to the use case.  Now I just have to see if I can get the `control routing` working as I imagine.

p.s. Thx for Bibliopixel!

![arduino pi midi control](https://user-images.githubusercontent.com/3280180/69653330-06218480-1041-11ea-8279-2d27d755a63d.gif)
