### ISSUE TITLE
bp monitor midi

### ISSUE THREAD

**Issue by VonHirsch** [ManiacalLabs/BiblioPixel#1145]
Hello, me again :) I have midi control_change messages coming through on the mido [receive.py example](https://github.com/mido/mido/blob/master/examples/ports/receive.py), however the output of bp monitor midi is blank, even though I can see it's listening to the correct port?

see below output of:

```
list_ports.py
receive.py 'ttymidi:MIDI out 128:0'
bp monitor midi
```

![bp_monitor_midid](https://user-images.githubusercontent.com/3280180/69348240-da1e9180-0c43-11ea-8994-31b285d13010.JPG)

Any ideas why receive.py sees the midi messages but bp monitor doesn't?

Thanks for your help!

**Comment by VonHirsch** [comment]
I may have answered my own question, is it that i'm getting:

`'channel', 'control', 'value', 'time'`

rather than:

`'port', 'channel', 'type', 'control', 'value'`

?

thanks

**Comment by adammhaile** [comment]
@VonHirsch - I'll be honest, I'm not sure and I've got no real way to test. The MIDI stuff was implemented by someone who is no longer involved with the project and was never really documented fully. It was really a pet project and I've never had the equipment to actually use the feature.

**Comment by VonHirsch** [comment]
@adammhaile ok no worries, understandable.  I'm going to pull down the src to my machine and try a few simple modifications to midi.py.  I'll let you know what I find out.
