### ISSUE TITLE
Error handling loses stack traces

### ISSUE THREAD

**Issue by iceboundflame** [ManiacalLabs/BiblioPixel#1151]
Currently stack traces are completely swallowed and as a result errors are hard to debug with non-specific messages -- it would be better to log exceptions with log.exception() instead of log.error(). As a starting point, the following hack helped me a lot: https://github.com/iceboundflame/BiblioPixel/commit/8b68beb60890795e5413d6f9c8c440ab7f5ac4c4

**Comment by adammhaile** [comment]
Yeah... the intent there was to keep scary stack traces out of users view and just "properly" handle them instead with various error handling. But it doesn't always work if completely unexpected errors pop up. 
Honestly not sure if I'd want to take the change you made as it could have other effects. Gotta think about it.

**Comment by iceboundflame** [comment]
Agreed, the change I made isn't really correct because we don't want to replace all `log.error()` calls with `log.exception()`, as not all `error`-level log entries have an exception to log. It'd probably be better to call `log.exception` from every site that's currently swallowing an exception.

**Comment by iceboundflame** [comment]
The PR above is the cleaner approach I mentioned; what do you think?
