### ISSUE TITLE
more docs on use of BP in library mode (in particluar Split() animations)

### ISSUE THREAD

**Issue by ozel** [ManiacalLabs/BiblioPixel#1155]
BP's flexibility fits great to my current use case of controlling a quite large and irregular LED structure (lots of grouped circles plus a large matrix made of alternating strips).
For faster development, I'd like to stay with the library mode and write everything in a python module instead of using static project files. I've hit the following issues which I think are related:
- animation.run() works (if based on a Sequence()) but throws a deprecated warning. What is currently the preferred way of launching animations from Python? Latest user forum posts and also the old wiki suggest calling .run() (https://github.com/ManiacalLabs/BiblioPixel/wiki/Projects)
- Calling a python module from the BP CLI as an alternative to static project files and as discussed/added in #494 ('bp [strip1.py](https://github.com/ManiacalLabs/BiblioPixel/blob/master/projects/strip1.py)') does currently not work (ModuleNotFoundError: No module named 'strip1' - ImportError: Cannot import symbol 'strip1.py')
- as a last straw, I tried following the code which calls the demos. in particular `bp demo circle` which provides the detailed kind of programmed project setup that I'm looking for. But so far I haven't managed to recreate a successful project construction from python like the BP demos.
- I want to use the Split() animation type. Add_animation() like in case of a Sequence(), does not work with Split(). How should Split() objects be constructed when using BP in library mode?

In general, I may have misunderstood the current aims of the project as the latest docs only describe the BP CLI and project files. Do you plan to deprecate all non-project-file-based use of BP and plan changing it into a CLI-only software? (I hope not ;) If you can provide me with some pointers, I'm happy to extend the docs regarding library mode usage.

**Comment by adammhaile** [comment]
Yeah - besides writing your own animations the plan was to deprecate anything other that yaml project files and we were well on the way to doing that when the project stagnated a bit.
Not sure what hardware you are using but if you are ok with using py2 instead of py2 it's still possible to just use the older BiblioPixel 2 -> https://github.com/ManiacalLabs/BiblioPixel2

I'm also in the process of writing a completely new library that keeps the hardware agnostic platform but trims all the fat of bibliopixel. You ONLY can do things from code in that library. Eventually BiblioPixel will be marked EOL and for things like the AllPixel and PiPixel we will only support the new library. But that's a year or more off (deprecation, not the new library).

**Comment by ozel** [comment]
thank you for the quick clarification! I should be staying with py3 and I need the advanced features of BP3 like Split() animations anyway. 
Where is the problem in my use of Split() here?
```
# setup of 16 LED coordinates in two rings of each 8 LEDs
driver = SimPixel(num=len(num_points), pixel_positions=num_points) 
layout = Circle(driver, rings=num_rings) 
```
The following starts the server and the animation according to logs but results in a stalled script and a warning about execution time:
```
anim = Split(layout,size=8)
anim.add_animation(CircleBloom(layout))
anim.add_animation(Swirl(layout))
anim.run(fps=20)
WARNING - animation_threading - Frame-time of 50ms set, but took 83ms
```
This variant of calling Split() stops with an error:
```
anim = Split(layout,size=8, animations=[CircleBloom(layout), Swirl(layout)])
anim.run(fps=20)
AttributeError: 'CircleBloom' object has no attribute 'threading'
```
The `bp demo circle` code is really the closest to what I need (with many additional splits across several rings). I also tried setting pixel_positions in the YAML project file but it doesn't work. I am assuming this one of the reasons why an API/library-way of setting things up is used for the circle demo and circle() is called, instead of using the CIRCLE_PROJECT variable also defined in [demo_table.py](https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/main/demo_table.py)?
For now I'm interested in simulating animations using the awesome SimPixel browser simulator which is what drew me to BP. I haven't seen anything comparable that gives the same flexibility for developing arbitrary structures. Eventually, the data must be routed via ARTNET adapters to WS281x LEDs.
