### ISSUE TITLE
How do I write this for c#

### ISSUE THREAD

**Issue by d8ahazard** [ManiacalLabs/BiblioPixel#1158]
Do you have an API reference or anything that I could use to understand how I'd write a version of this library for c#/.net core? 

I'm already using you PiPixel, but I'd like to consider adding support for the AllPixel as well, and with a bit of reference, I'm sure I could manage this quite easily.

Tia...

**Comment by adammhaile** [comment]
Sure, the protocol is incredibly simple and detailed here: https://github.com/ManiacalLabs/BiblioPixel2/wiki/DriverSerial#protocol

If you've got any questions while you are working on your C# port of the API, feel free to hit us up on the forum: https://forum.maniacallabs.com/
