### ISSUE TITLE
New Feature: Spectrum Analyzer

### ISSUE THREAD

**Issue by Pushpit07** [ManiacalLabs/BiblioPixel#1163]
I was working on a project and wanted to construct this- https://www.instructables.com/Raspberry-Pi-Spectrum-Analyzer-with-RGB-LED-Strip-/
This is probably one of your older projects.

I tried a lot to achieve this but was unsuccessful. Can someone probably help in creating this if it is possible using BiblioPixel?

**Comment by Pushpit07** [comment]
<img width="463" alt="Screenshot 2021-03-20 at 18 16 00" src="https://user-images.githubusercontent.com/57194612/111870109-c5255000-89a8-11eb-9e7e-ee21c38f7f90.png">

**Comment by adammhaile** [comment]
There's already a similar animation here: https://github.com/ManiacalLabs/BiblioPixelAnimations/tree/master/BiblioPixelAnimations/matrix/spectrum
