### ISSUE TITLE
 setHSV will not work for me

### ISSUE THREAD

**Issue by fluesternBlock** [ManiacalLabs/BiblioPixel#12]
I use the class LEDMatrix. I tried to call matrix.setHSV(10, 10, (240, s, v))
But nothing happened. No LED is on. I tried hsv = (240, 100, 100); hsv = (240, 1, 1); hsv = (240, 1.0, 1.0)
But nothing happend. 
The color should be blue. I think I have a logical failure. Please help me.

**Comment by adammhaile** [comment]
Can you send all the code you are using? Will help me diagnose. SetHSV
should work...

**Comment by fluesternBlock** [comment]
Yes. I think so, but i am do something wrong. Could you give me an example call oft this Methode for one pixel Plesse? Thanks.

**Comment by adammhaile** [comment]
No, no, I want to see your code. Are you calling led.update() ??

**Comment by fluesternBlock** [comment]
This is my "small" example for using hsv:
driver = DriverLPD8806(200, ChannelOrder.BRG, True, SPISpeed = 2)
led = LEDMatrix(driver, 20, 10, rotation = MatrixRotation.ROTATE_0, vert_flip = False, serpentine = False)

h = 240
s = 100
v = 100

led.setHSV(10, 10, (h, s, v))
led.update()

This example and my example for the whole matrix don't work. I don't know what I am do wrong.
Please help me.

**Comment by adammhaile** [comment]
Ohhhhh... Your matrix is 20 wide and 10 high. But pixel coordinates are
0-indexed. So the indices are x:0-19, y:0-9
So, (10,10) is out of bounds (below the matrix).
What you probably mean is (9,9).
To be sure your matrix is working, try led.fillScreen((255,0,0)) which
should fill the screen red.

**Comment by fluesternBlock** [comment]
Oh.. sorry. That's my fault.
I tried it with the following code:
driver = DriverLPD8806(200, ChannelOrder.BRG, True, SPISpeed = 2)
led = LEDMatrix(driver, 20, 10, rotation = MatrixRotation.ROTATE_0, vert_flip = False, serpentine = False)

h = 240
s = 100
v = 100

led.setHSV(0, 0, (h, s, v))
led.update()

But I become an error:
INFO - spi_driver_base - py-spidev speed @ 2.0 MHz
Traceback (most recent call last):
  File "hsv.py", line 18, in <module>
    led.setHSV(0, 0, (h, s, v))
  File "/usr/local/lib/python2.7/dist-packages/bibliopixel/led.py", line 324, in setHSV
    self.setHSV(pixel, hsv)
TypeError: setHSV() takes exactly 4 arguments (3 given)

The method of LEDMatrix.setHSV could invoked correctly. But the method of the super class not. 
I think, I still do something wrong.

**Comment by adammhaile** [comment]
Ahh... that's a bug. Grab the latest version. Fixed it now.

**Comment by fluesternBlock** [comment]
Me again.
Thanks for your help!! It works!!
My color changing code works fine. This is so amazing. ;-)
Thanks for your library. Great work!
If I got my plexiglass and I built the frame for my matrix I will post some pictures/videos.
