### ISSUE TITLE
Help the user discover, test and set up hardware devices 

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#127]
and store them in .bibliopixel.

From #113.

**Comment by rec** [comment]
@adammhaile - so I'm not planning too much for this, basically letting them pick from a list of devices and running a simple test program.

Is there any form of discovery that we can easily do for some of these devices?  Is there a way to easily see if there's an AllPixel or more than one attached to the USB port?

**Comment by adammhaile** [comment]
Yup, super easy: https://github.com/ManiacalLabs/BiblioPixel/blob/dev/bibliopixel/drivers/serial_driver.py#L129
That will find ONLY AllPixels. Note this will not find the controllers on the 12k... that has a different VID/PID pair. But you can see where that is passed into that method.
