### ISSUE TITLE
Run as a client/server for networked BP.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#128]
Taken out of #113.

Not for 3.0...?

**Comment by adammhaile** [comment]
Kinda depends on what this means... for one, I still want a way to wrap up a project in a simple web UI front end. Doubt that's going to happen in 3.0 though... probably 3.1 (it's very high on my priority list as 3.0 completely breaks PixelWeb).

**Comment by rec** [comment]
Perhaps a new 3.x milestone?

**Comment by adammhaile** [comment]
Yeah... should be.
