### ISSUE TITLE
Add Travis rule to prevent wrongly formatted text files.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#130]
We should ideally be checking two conditions - 

* that the files are not in DOS format (i.e. that they only have `\n` at the end of lines and not `\n\r`) 
* that files are UTF-8 encoded!

It's fine if we don't get the second one done in this iteration.  Or, frankly, the first either. 

Encoding is worth checking because surprisingly some codebases don't just have mixed encodings between files, but mixed encodings _within_ a single file.  An actual example I ran into was a codebase where every file had legal boilerplate at the top with a Latin copyright symbol in it, and then some of the code had UTF-8 inline.

This meant that no automatic tool could process such files correctly without some clever trick or other to preserve the mixed encoding...

**Comment by adammhaile** [comment]
Yeah... let's make this 3.x (or as we'd call it at Red Hat, 3.next)
