### ISSUE TITLE
Many more demos.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#133]
We have the ability to add a lot of existing slick demos from BPA to the main demo program - we should do so because it's impressive and costs us little.

**Comment by rec** [comment]
I'm unassigning myself here.  :-D

The existing "circle" demo doesn't work.  Indeed, I had likely never tried it because it was referring to a non-existent class in BPA and dies before it starts (see upcoming pull request to fix).

I fixed the gross error, but now it runs and does nothing.  Will defer to you @adammhaile on this one!

**Comment by adammhaile** [comment]
Yeah... I need to make a BPA3 or something. Too much is breaking there are
no longer compatible with both. Will fix.

**Comment by rec** [comment]
We can launch 3.0 with the demos we have.

**Comment by adammhaile** [comment]
Done with 3.0.2
