### ISSUE TITLE
Error running text_demo.py (Problem communicating with network receiver)

### ISSUE THREAD

**Issue by LeoDJ** [ManiacalLabs/BiblioPixel#15]
Hi Adam,

I was just getting startet with the interface for my POV Display (because the mechanics aren't completely done yet) and my goal for this day was getting a gif to be displayed (just on the strip without pov) to test the library. 
So I startet by running the text_demo.py The Visualizer windows appeared, but the pixels (of the visualizer) just stayed blank and following error was written to the terminal:

    pi@RaspberryPi-PoV ~/LEDstrip/BiblioPixel-master $ sudo python text_demo.py 
    ERROR - network - [Errno 111] Connection refused
    Traceback (most recent call last):
      File "/home/pi/LEDstrip/BiblioPixel-master/bibliopixel/drivers/network.py", line 55, in update
        s = self._connect()
      File "/home/pi/LEDstrip/BiblioPixel-master/bibliopixel/drivers/network.py", line 45, in _connect
        s.connect((self._host, self._port))
      File "/usr/lib/python2.7/socket.py", line 224, in meth
        return getattr(self._sock,name)(*args)
    error: [Errno 111] Connection refused
    ERROR - network - Problem communicating with network receiver!
    Traceback (most recent call last):
      File "text_demo.py", line 18, in <module>
        scroll.run(fps = 20, untilComplete = True, max_cycles = 2)
      File "/home/pi/LEDstrip/BiblioPixel-master/bibliopixel/animation.py", line 59, in run
        self._led.update()
      File "/home/pi/LEDstrip/BiblioPixel-master/bibliopixel/led.py", line 100, in update
        d._update(self.buffer[pos:d.bufByteCount+pos])
      File "/home/pi/LEDstrip/BiblioPixel-master/bibliopixel/drivers/driver_base.py", line 44, in _update
        self.update(data)
      File "/home/pi/LEDstrip/BiblioPixel-master/bibliopixel/drivers/network.py", line 75, in update
        raise IOError(error)
    IOError: Problem communicating with network receiver!

So, I'm not sure what's going on here, but it seems to have to do something with the network interface, even though I'm not using it anywhere. 
Because I don't know the library code as good as you, I didn't bother looking for too long in the source code (I didn't find anything in half an hour). So instead, I installed python and the library (including dependencies and Tkinter) on my windows machine and still got the same error.

It would be really nice if you could help me with this issue ;)

Regards 
LeoDJ

**Comment by adammhaile** [comment]
Visualizer actually uses TCP sockets to communicate between BiblioPixel and the Visualizer process. Did you modify the demo code at all?
I'll have to look tonight... at work right now. Should likely be something simple(ish).

**Comment by LeoDJ** [comment]
Ah, okay, that explains the error a little bit :P
I didn't modify the demo.
I'm also getting the same error, if I use the visualizer driver in my example script, which runs fine using the APA102 driver

Thanks already in advance ;)

**Comment by adammhaile** [comment]
Gotcha.... something must have been broken with the Visualizer then. Weird... works fine for me. Used it last night. Maybe firewall thing? But you said on Pi and Windows. I'll figure it out... hopefully I can reproduce it. Are you using the latest stable code?

If you do this, what does it print?

```python
import bibliopixel
print bibliopixel.VERSION
```

**Comment by LeoDJ** [comment]
1.1.7

I got it straigt from GitHub

**Comment by adammhaile** [comment]
Ok... cool. Just checking

**Comment by adammhaile** [comment]
Not sure what to tell you, I just tried it. Copied down fresh from GitHub
and ran the text demo with no problem.
Seems like you have some firewall or something blocking the network traffic
even if it's internal.

**Comment by LeoDJ** [comment]
Well, I just installed it again on a completely fresh Win10 Virtual Machine (I didn't have any other VM laying around)

And did the following steps:
* Install Python 2.7.9 (and restart)
* Download and extract bibliopixel from github
* run "python setup.py install"
* try to run "pip install pillow" (worked on main PC and Pi, but didn't in Win10, shouldn't be necessary for text_demo.py anyway)
* run "python text_demo.py"

-> same error as before
(Full install vid: http://youtu.be/fT-MEON53Ww)

I'm pretty sure, I'm just doing a stupid error somewhere, but I can't imagine what it could be :/

I'm glad that you're helping me so much, thanks again ;)

**Comment by adammhaile** [comment]
Random thought... since I don't see anything specific...

In bibliopixel/drivers/visualizer.py

There is this line at the top:

        super(DriverVisualizer, self).__init__(num, width, height, host =
"localhost", port = port)

Change to:

        super(DriverVisualizer, self).__init__(num, width, height, host =
"0.0.0.0", port = port)

My guess is that it's not listening on the localhost properly for some
reason. Using 0.0.0.0 will listen on all interfaces.

BTW... for testing this you don't need to install BiblioPixel. I would
actually uninstall (setup.py uninstall) and then edit the file in the
folder you downloaded.

Still no idea why this would be the case with multiple systems for you but
it's my best guess at the moment.

**Comment by adammhaile** [comment]
Wait! I watched the video again and I know the problem....

The visualizer is taking too long to load... so it's not available to
connect to. Run it again, but don't close the visualizer after it fails.
Then run text_demo.py again... it will connect to the visualizer that
opened in the first attempt.

I may need to add a delay after the Visualizer load...

**Comment by LeoDJ** [comment]
Hey, yeah, you're right!

**Comment by LeoDJ** [comment]
That's it, thanks! Now I can go on testing without the moving LEDs, thank you so much! I really appreciate your work!

**Comment by adammhaile** [comment]
Sweet! :) Thanks so much for doing the video! That was what made it
possible to figure it out :)
There is actually a 500ms sleep already, but for some systems that's
obviously not long enough.
Easy fix... but for now, just run once, let it fail and then run the script
again. No need to close the UI each time.

**Comment by LeoDJ** [comment]
Yes, changing the sleep at the end of visualizer.py to 2 seconds has done the trick. Now it works fine!

**Comment by adammhaile** [comment]
Awesome :) I'll make that change in the next release.
