### ISSUE TITLE
Animation frame time occasionally falls short by a few milliseconds.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#154]
Like this: `WARNING - base - Frame-time of 0ms set, but took 0ms!`

**Comment by adammhaile** [comment]
I was wondering about that... I think that I thought it was that other similar bug I found earlier. But you already fixed that :P

**Comment by rec** [comment]
I didn't see the obvious problem or I'd have fixed it!

**Comment by rec** [comment]
So now there are better messages, it's clear that there's a real, but subtle, issue here.

I am intermittently seeing things like:

    WARNING - animation_threading - Frame-time of 33ms set, but took 34ms!
    WARNING - animation_threading - Frame-time of 16ms set, but took 25ms!

in the matrix demo.  However, I don't think that we really are running out of time rendering the frame - I can speed up or slow down the frame rate considerably with no change in these messages.
