### ISSUE TITLE
Stern warnings when using the `//git/` prefix;  make auto-pull configurable.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#199]
With the new path feature, we're basically allowing people to download and run other people's un-audited Python code at user perms on their box!

More, if I select HEAD and not a specific commit - with the auto-pull, which is set on by default, it pulls the remote repo each time.

Which that I can audit someone's code, link to HEAD, and then that attacker can commit malware which will automatically be pulled into my code area.

More, I can run a project from someone's site, which leads to code from another site, and not know any of this.

(I knew this thing was there all along but didn't deliver a fix in the first pass.  Also, I wanted to see if you'd complain. :-D)

**Comment by adammhaile** [comment]
I had that thought... But same could happen any time you pip install
something. BP 3.1 could be pure malware. I say we say "use at your own
risk" and call it a day.

Note... When using AllPixel many people are too lazy to set dialout perms
and run scriptd as root! But again... That's their risk :P

**Comment by rec** [comment]
Closed in favor of https://github.com/ManiacalLabs/BiblioPixel/issues/354
