### ISSUE TITLE
RPi: to use spidev1.0 or other GPIOs

### ISSUE THREAD

**Issue by akrv** [ManiacalLabs/BiblioPixel#21]
Hi, I want to use the pins 38, 40 in the RPi GPIO(BOARD) for SPI  MOSI and SCLK respectively. (http://pi.gadgetoid.com/pinout/pin40_gpio21)
I m using the /dev/spidev0.0 for other devices.
Or is it possible to use may be two of the GPIO to use the LPD8806 based strip?

**Comment by adammhaile** [comment]
Would you mind moving this to the BiblioPixel support forum? We try to keep the github Issues list to actual bugs. I'm looking into the answer for this and will respond on the forum. Thanks! 

http://forum.maniacallabs.com/forumdisplay.php?fid=8

**Comment by adammhaile** [comment]
Moved to: http://forum.maniacallabs.com/showthread.php?tid=51
