### ISSUE TITLE
Replace lost WS 281x driver that was based on a C library

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#213]
In the discussion of #208, it came up that there had been a C library based SPI driver that had the great negative of depending on an external C library but the positive of handling larger display sizes - a library that had accidentally been deleted without being replaced.

**Comment by TuxCoder** [comment]
I'm not sure what you mean, the old spidev driver is available via

´´´python
from bibliopixel.drivers.LPD8806 import LPD8806
from bibliopixel.drivers.spi_driver_base import SpiPyDevInterface
driver = LPD8806(42, interface=SpiPyDevInterface)
´´´

**Comment by adammhaile** [comment]
What we talked about before... Actually the issue name is wrong. Replace
lost WS 281x driver that was based on a C library

**Comment by rec** [comment]
@TuxCoder - nah, this is our mistake which came up in your review.  Sorry to have bothered you!

**Comment by adammhaile** [comment]
Complete in #229
