### ISSUE TITLE
Replace AllPixel test program with `bibliopixel`.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#214]
[This page](https://github.com/ManiacalLabs/AllPixel/wiki/Library-Install-and-Strip-Example) must lose all its code.

It must be replaced by some single line that looks like:

    bibliopixel [...]

This means that we need some way to pass the LEDTYPE into `bibliopixel`.

**Comment by adammhaile** [comment]
Nope.... it's still valid for when you want to use actual code.
Yes, we need another section or page that has the new way to do it, but this is still totally valid.
And yes, we need a way to pass in LEDTYPE, but that's out of the scope for this release. Moving this to a later release.
