### ISSUE TITLE
Threaded run not working

### ISSUE THREAD

**Issue by jimnet2005** [ManiacalLabs/BiblioPixel#22]
This is an issue related to the /dev branch. When trying to run an animation using the "threaded = True" method: the thread simply does not run. The issue is related to the line 156 of animation.py, in which you get the locals() dictionary. Within the following lines you attempt to remove some members from the locals() dictionary which seems to be an invalid operation as even the local "self" reference is removed.

The best workaround I've seen for this is replacing the line 156 with the following:

args = locals().copy() # gets a copy of the locals() instead of the actual locals

Regards,

Jaime

**Comment by adammhaile** [comment]
could you send me the basic code you are using and on with what system
details? I'm not seeing it fail on my end... although, I think I see what
you mean and am putting in a fix. I'm guessing that on some version of
python or systems, locals() gets the actual dictionary in use and then
modifies it... which is obviously bad.

**Comment by jimnet2005** [comment]
Yes. The code is the same as you have on you /dev branch. Actually managed to run your https://github.com/adammhaile/PixelWeb code with just a few adjustments (e.g. set anims directory). I'm working on Raspberry Pi model B with python 2.7

**Comment by adammhaile** [comment]
Hmmm... OK. I haven't really tested this on the Pi yet. Probably why.
I've commited a fix for it that should hopefully work for you.
Could be getting back to PixelWeb work now :)

**Comment by jimnet2005** [comment]
Great. Thanks.

Actually, I just realized that the "self" reference is removed in "my own code" because I'm forcing to do so. The real issue is that the pop() method is not working at all on my raspberry, and the code crashes when trying to invoke the run() method on the animation without removing "callback, self, threaded, ... etc" from the dictionary. Hopefully the workaround effectively fixes the issue and allows the ode to remove the unwanted dictionary members.

**Comment by adammhaile** [comment]
That was my guess... so instead of popping, I build a new dictionary by
appending. Hopefully that will fix it. I'll look into why pop doesn't
work...

**Comment by jimnet2005** [comment]
Your choice. Creating the locals.copy() instance just works very well and seems to be logical. I'm a python newbie, but I suppose the raspbian python just does not allow you to screw things up by modifying the locals(). I had to call the method on a second occasion (through my IDE) do so.

**Comment by jimnet2005** [comment]
Side note: pop() does not work with the locals(), but does work well with the locals.copy()

**Comment by adammhaile** [comment]
Good to know. thanks :)

**Comment by lucalamo** [comment]
hi, adammhaile i would ask you if is possible to add UCS1903 drivers, i'm trying to use your project with a raspberry pi.

Thanks

**Comment by adammhaile** [comment]
@lucalamo This isn't really the place for feature requests and it's not related to this bug, which should be closed anyways. Would you mind posting your request here? http://forum.maniacallabs.com/forumdisplay.php?fid=8
