### ISSUE TITLE
Most gitty paths will automatically fail if you have no network connectivity.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#220]
Suppose you develop your project on a machine that's connected to the internet, and then move that machine off the net.

If you have a specific commit for your gitty path, you are probably fine - I need to look at the code - but if you use a branch, it will try to refresh that branch and die.

The solution is a command-line argument to suppress those failures.

**Comment by adammhaile** [comment]
Totally fine with that as long as if you do get one of those failures it
shows, very clearly:
"Use --offline-git to suppress these failures" or something like that.

**Comment by rec** [comment]
https://github.com/timedata-org/gitty/issues/6
