### ISSUE TITLE
Fix wiki/Hardware-Commands

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#222]
See https://github.com/ManiacalLabs/BiblioPixel/wiki/Hardware-Commands

**Comment by rec** [comment]
We only have these two issues to the next milestone!

**Comment by adammhaile** [comment]
Yeah... been putting this off. Will do shortly.

**Comment by rec** [comment]
Closing this as too specific.  We need to prepare a complete master list of all the documentation we need and then finish it all and filing one bug per document is just silly.

**Comment by rec** [comment]
All right, there are too many documentation bugs already filed...
