### ISSUE TITLE
Projects should auto convert all valid enums from strings

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#237]
Realized just now that I cannot set c_order in projects! :(
You should be able to just enter either "GRB" or "ChannelOrder.GRB" and it should work. Problem is that now the new ChannelOrder code requires a tuple input. I can input a list in the project but list!=tuple :(

We did this a little for things like LEDTYPE but we need handling for this ASAP.

**Comment by adammhaile** [comment]
Hmmm... ideal is that project.py looks at values and sees if they match any known enums. 
However, damn, ChannelOrder is a class not an enum. 
Ok... right now the "simpler" but less global solution is to simply handle the string to ChannelOrder conversion in the driver.
Ok... perfect, since c_order is no handle in DriverBase, this is super easy. Fix incoming. 

But we still need more global support for this and other types/enums. Leaving open for those.

**Comment by adammhaile** [comment]
#238 Fixes the ChannelOrder issue. Leaving open for handling *all* options.

**Comment by rec** [comment]
I believe this is fixed as part of "special values" so I am closing it.  If there are specific parts that are missing, we can file specific bugs.
