### ISSUE TITLE
projects.py level global pre-processing of special values

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#242]
Thanks to @haooken for pointing this out.

There are several special types of values that are settable inside a project by using a more raw representation but not by a nice, human friendly, value. We want projects to be human friendly.

For example, colors. Right now you have to enter [255, 0, 0] instead of colors.Red.

All of these special types internally are part of an enum or class so we can key off that.

Options are:

colors
LEDTYPE (this is a little weird becacuse there's two... serial and SPI)
Rotation
gamma

Probably more. Can't find them right now.
What I recommend is we register those types then look for the type followed by a period. If so, we try to resolve and replace that value inside the dictionary. 

Yes, this requires blindly walking the whole dictionary. But that's not really too hard.

This will make projects much cleaner to use and read.

**Comment by rec** [comment]
1. We clearly need to do this quite soon!

2. Two different `LEDTYPE`s is a bug. But is this really true?  I don't see this in the code...?

3. A hardcoded table from "property name" to "property constructor" might do it really quite well.

4. We could also inspect the class constructor if we wanted to get fancy, but is the table really bad?  It's certainly clear, explicit and easy to write.

**Comment by rec** [comment]
I did a little research.

If we were willing to move our minimum requirement to Python 3.5, there is a complete solution for this - [type annotations](https://docs.python.org/3.5/library/typing.html) in the class constructors.

That might be tricky, but would nail the problem forever.

I have an alternative Python 3.4 version in client which uses single dispatching and classes to do an OK job.

**Comment by adammhaile** [comment]
Python 3.4 is still too pervasive in terms of default Python 3 installed
version that we can't move to 3.5 yet.
Maybe in a year or two we can swap out how it does that, but I'd rather
handle it our own way for now.
