### ISSUE TITLE
Allow users to create their own aliases (and store them in the settings file).

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#245]

**Comment by adammhaile** [comment]
What settings file? In the project json file? Or something more global? I guess I thought that went away :P
My only concern here is then sharing that project file without the global settings file including the aliases would cause problems.

Two thoughts on this...

- I already wanted to add `bibliopixel gen_project_template` or something that would spit out a template to start from to whatever file you specified.
- Now I think we should add `bibliopixel dist <project_file>` or similar, that would resolve any aliases or anything else that might be user local specific.

**Comment by rec** [comment]
The settings file still exists - we just don't put anything in it!

> My only concern here is then sharing that project file without the global settings file including the aliases would cause problems.

:-o

That's actually a really good point that cannot be gotten over.

If we dump custom aliases, do we really need `bibliopixel dist`?  What else do we get out of it?  

Are we really going to look at all the cruft that people have installed in the PYTHONPATH and force this on all users of their casual one-liner JSON?

I think we should not have a `bibliopixel dist`. I think we should be encouraging people to use as bare a virtualenv as possible and instead rely on gitty loading for all their third-party projects.
