### ISSUE TITLE
Close or reassign all milestone 3.0 issues.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#246]

**Comment by adammhaile** [comment]
I've made a 3.0.x milestone. As in, not bigger new stuff but things that we should likely fix on the current version. One remaining 3.0 issue which is the hardware doc stuff I've been putting off. Will do today.

**Comment by rec** [comment]
I moved that hardware doc bug to 3.0.x, on the theory that 3.0 is already in the past.  Now closing this one.
