### ISSUE TITLE
LPD6803 Support Missing

### ISSUE THREAD

**Issue by praeluceo** [ManiacalLabs/BiblioPixel#26]
The LPD6803 LED driver has gamma support in bibliopixel/pixelweb but no support under LED Type. When selecting the other LPDx drivers some pixels light, but not all of them, and they do not appear to accurately reflect the RGB channel order. I don't personally have this strand for test, but was discussing the matter with a friend who does, and I noticed that LPD6803 is in-fact missing from the configuration options despite being present under gamma.

**Comment by adammhaile** [comment]
I will remove it from gamma.py 
We do not support the chipset. It's very old.

**Comment by praeluceo** [comment]
I don't think you get to close the ticket until -after- the code is updated.
(;

**Comment by adammhaile** [comment]
:P Details. It's removed now... but just on GitHub. Not really a big enough change to rev the version number and push to PiPy
