### ISSUE TITLE
Command line flags are position-dependent.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#261]
`bibliopixel  --verbose run --animation=matrix_check` works, but

    $ bibliopixel run --verbose --animation=matrix_check 
    usage: bibliopixel [-h] [--loglevel {debug,info,warning,error,critical}]
                       [--path PATH] [--verbose] [--version]
                       {all_pixel,clear_cache,demo,devices,run} ...
    bibliopixel: error: unrecognized arguments: --verbose

NOTE:  this is a known issue with how `argparse` works with separate commands, not a bug in our code.  However, I can see two ways of getting around this...

**Comment by rec** [comment]
Fixed!

**Comment by rec** [comment]
No, still, an issue:

    # works
    bibliopixel --loglevel info demo bloom --numpy
    bibliopixel --loglevel=info demo bloom --numpy
    bibliopixel --loglevel=info demo --numpy bloom

    # doesn't work
    bibliopixel demo --loglevel info bloom --numpy  
    bibliopixel demo bloom --numpy  --loglevel info

**Comment by rec** [comment]
Nope, it wasn't fixed, that's why I reopened it!  See the example above.

**Comment by adammhaile** [comment]
Oh... shit. That was because the fix was mentioned in a commit that just got pushed up to master so it reclosed it :P

**Comment by rec** [comment]
Really fixed this time!

**Comment by adammhaile** [comment]
Sure it is....
