### ISSUE TITLE
Allow projects with multiple, heterogeneous drivers.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#264]
BP projects only support multiple drivers if the drivers differ only by device id - that means if things like width, height, or serpentine change are different, you're out of luck.

This also results in a hard-to-explain data format.

We should fix this, and then fix #263 with the new documentation.

**Comment by adammhaile** [comment]
Ah, yes... absolutely :)

**Comment by rec** [comment]
Regarding backwards compatibility here, my goal is to have this backward compatible with 3.0 for _single_ driver projects that already exist, but _not_ for multiple driver projects - since we never documented those and it's my strong belief that I'm the only one who has any multi-driver projects.  :-)

**Comment by adammhaile** [comment]
Perfectly acceptable
