### ISSUE TITLE
Support missing pixels in Layouts by allowing `None` as a pixel.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#271]
This is part of a bigger picture, so don't comment just yet.  :-D

---

It would be advantageous for a layout to have the possibility of returning `None` for a given index.

A moderately small number of changes would have to be made on existing code within BP.  More, we could do this piece at a time, because it doesn't hurt if code handles `None` but never actually receives such a thing.

This would not impact existing third-party code at all - it would just expand the possibilities of new code.

**Comment by adammhaile** [comment]
This is already possible. And I use it frequently. If set_pixel() gets `None` for the index it should just ignore it and return.

Hmmm... actually shite... it does not anymore: https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/layout/layout.py#L50

In python 2: (None >= 0) would result in False.
In python 3: (None >= 0) throws an exception. Yeah, that needs to be fixed.

**Comment by rec** [comment]
I think I saw a couple of other spots too.  I'll get to it.  :-)

**Comment by adammhaile** [comment]
Awesome

**Comment by rec** [comment]
Will not fix.  Conflicts with making our ColorLists `memoryview`s.
