### ISSUE TITLE
Attempting to read from or write to non-existent positions in layouts has variable and undesirable results.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#272]
What happens when an Animation reads or writes out-of-bounds to a layout?

The usual behavior is an exception that causes processing to stop.  

Dying miserably is pretty awful behavior for a real-time program:  "I walked off the end of this array - and the whole room went dark!"

(Also, we inconsistently accept negative indexes in some cases but not others.)

An out-of-bound read or write should have the following possible behaviors:

1. do nothing/return `None` (dependent on #271)
2. print a message the first N times this happens (where N might be infinite).
3. throw an exception

The default behavior should be 1 - nothing.

It should be possible to configure the program to do 2. or 3. either globally or specifically for any individual layout, and separately for reading and writing.

**Comment by adammhaile** [comment]
As noted in #271, this used to work in BP2 but Python 3 changes broke it. Yes, absolutely, we should just do nothing if an out of bounds index is passed.
