### ISSUE TITLE
More graceful quit

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#276]
Unless I'm missing something, the only way to quit out of `bibliopixel run` is Ctrl+C. Which works, but it barfs a big exception to the console. We should capture this and handle it gracefully, shutting down all threads and exiting. As I add the remote control stuff this is especially important as the control UI server runs on a full separate process.

**Comment by rec** [comment]
Or you might get to it before I do, as I am running out of time for a bit...

**Comment by adammhaile** [comment]
Yeah... I kinda figure I might ;)

**Comment by adammhaile** [comment]
This is fixed in upcoming push... but more to do on that.

**Comment by adammhaile** [comment]
Fixed quite nicely in the `remote` branch.
