### ISSUE TITLE
Allpixel Serial Interface Failure

### ISSUE THREAD

**Issue by praeluceo** [ManiacalLabs/BiblioPixel#28]
Issue Summary:
Allpixel not properly detected by pyserial and fails to be accessible, or even displayed in pixelweb.

Hardware Configuration:
* Raspberry Pi 2
* AllPixel (Kickstarter)

Software Configuration:
* Raspbian Wheezy
* Latest pip install of bibliopixel and pixelweb

Reproduce Steps:
* Install Raspbian and pip install all dependencies
* sudo run-pixelweb, note that network shows up, visualizer shows up, but not serial driver.

Characterization/Isolation:

The issue stems from pyserial on the RaspberryPi being version 3.0.1 instead of 2.6 I believe. When pixelweb is run, it fails silently, when DeviceIDManager.py is run, it dies with a python stacktrace (which I failed to retain) but the end result (if my saved Google search and memory serves) was "error invalid literal for float 3.0.1, expected 2.7".

Work around:
After verifying with lsusb that "1d50:60ab" was indeed present, and since the error terminated at line 15 of bibliopixel/drivers/serial_driver.py, I went to that section of the file and simply deleted that if statement. DeviceIDManager.py and AllPixelConfigure.py worked great now, so I went back to run-pixelweb and sure enough, the AllPixel shows up and works perfectly.

Ironically, that section was added in a commit with the goal of, "added better check for pyserial version":
https://github.com/ManiacalLabs/BiblioPixel/commit/7390812dd395071c46c2fa9de0287d7024effeb3

**Comment by adammhaile** [comment]
Ahh... yeah, pyserial didn't used to use a full major.minor.subminor version scheme. So that broke some kinda week code. I'll push a fix later tonight. Nothing complicated.
Thanks for pointing it out!!

**Comment by adammhaile** [comment]
Fixed
