### ISSUE TITLE
Clearer error messages for badly-formed projects.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#302]
If you do things like "not have a typename" or "have a list where a dictionary is expected" or a bunch of other likely errors, you get various weird tracebacks of no use to an end-user.

1. We must make it clear that there's an error in the user's project file, and which file that is.
2. We must at identify which section of the project and which value within that section the error is .
3. This is probably impossible, but pointing to the exact line would be nice.
4. We need to try a bunch of likely failures and make sure we fail gracefully and clearly for all of them.

**Comment by adammhaile** [comment]
+1
