### ISSUE TITLE
Clean Layout.cleanup, Animation.cleanup and Device.cleanup up.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#317]
There's an unpleasantness with [`Animation.cleanup`](https://github.com/ManiacalLabs/BiblioPixel/blob/dev/bibliopixel/animation/animation.py#L54-L62) that needs to be addressed - the sketchy `clean_layout` parameter.

I believe that _no_ cleaning should be done when switching animations, for the same reasons I outlined before - that you would want the results of the existing "screen" if you wanted to perform a smooth transition - but also because most animations overwrite everything every time, so why should they pay the cost?  And of course, this fixes the flicker issue as well.

Animations do need a cleanup phase - in case they have associated threads or processes.  
Layouts can't have threads or processes (we should make that an axiom!) so they don't need a cleanup.

It is _Devices_ that also need a cleanup phase that turns off all the lights - nothing worse than stuck lights! - BUT that should only be called at the end _of a project_ and at no other time - and even that behavior should be able to be turned off by a flag in the project.

**Comment by adammhaile** [comment]
Agreed. That is probably moot now. But at the time, cleanup always cleared
the display.
