### ISSUE TITLE
Document or delete BaseMatrixAnimation.startX and BaseMatrixAnimation.startY

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#318]
They are not used anywhere in BP.  

`startX` appears [once](https://github.com/ManiacalLabs/BiblioPixelAnimations/blob/master/BiblioPixelAnimations/matrix/Text.py#L29) in BPA, but is provably always zero :-D and even if the code were fixed, `startX` would be better off on that derived class in BPA.

**Comment by adammhaile** [comment]
Yeah... it was an idea that never really got used. I'll delete it.
