### ISSUE TITLE
We should be able to run directly from a gist.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#319]
$ bibliopixel run https://gist.github.com/rec/adb4bc48080a6505e73b945c1178f614
    ERROR: Expecting value: line 7 column 1 (char 6)
    in https://gist.github.com/rec/adb4bc48080a6505e73b945c1178f614

It's because it's not getting the raw data but the processed data.

Unfortunately, fixing that might require we use BeautifulSoup or something similar to parse the original file...

**Comment by rec** [comment]
This is fixed in gitty 1.2.2.

Should I be putting a minimum version for gitty in `requirements.txt` now?

**Comment by adammhaile** [comment]
I'd leave it alone so that people always get latest. The only problem we
have here is users that already installed BP and therefore have the old
version. Nothing to be done about that except tell them to update if they
have a problem.

**Comment by rec** [comment]
If you put a minimum version in, you always get the latest, but I'm happy not to do anything here.  :-D
