### ISSUE TITLE
pwd should always be on the path

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#323]
This is kind of in the interest of eventually only really supporting running BP from `bibliopixel run`, no direct scripting.... whaaaaaaaaat? Yes, you heard me.
If I call bibliopixel run, whatever directory I'm currently in should be on the python import path. Right now when I dev I have to manually add that path and it's annoying.
Better yet, whatever directory the json file is in (with a few blacklisted exceptions or files loaded from URL) should be on the path too. So if I call `bibliopixel run ./MyAwesomeDemo/config.json` and `MyAwesomeDemo` has my code too, it should just plain work.

**Comment by rec** [comment]
This is easy-peasy to do but I'm a little dubious about the second part.  Well, let me do it and then we can see if it causes trouble.  :-D

**Comment by adammhaile** [comment]
Agreed... having the config file path be on the path could be weird. I'd
settle for just pwd.
