### ISSUE TITLE
Now we have `.` in the path, scripts aren't necessarily exportable...

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#329]
...because they can refer to local functions that aren't visible elsewhere!

**Comment by adammhaile** [comment]
Not everyone is going to have all their code up in a git repo somewhere. This is a non-issue as it's still valid even if not ideal for sharing with the community.

**Comment by rec** [comment]
Absolutely it's an issue, because we need a way to prevent people from doing this when they _do_ upload!

Basically, as it works now, people will prepare their files and they will fail the first time for everyone.  Bad show.

It's not just `.`, it's also local files for datafiles.

Still thinking about this one... I think we'll eventually need a "validate local" or something.

**Comment by adammhaile** [comment]
As noted previously we need a distribute command that ensures a file is
globally usable.

**Comment by rec** [comment]
On it.  :-D
