### ISSUE TITLE
Add brightness control to remote UI

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#331]
Show whatever the current global brightness is in UI and allow changing.

**Comment by rec** [comment]
3.1.x? Surely this is an actual new feature of significance and not a minor version number update?

Do we need a 3.1.x milestone anyway?  At some point, we can just go for 3.2 and be done with it, even if we have to reassign issues in the 3.2 milestone to do this.

I would see 3.1.x as a bug fix to 3.1.(x-1), myself - but we don't have any actual bugs outstanding that can be so easily fixed.

**Comment by adammhaile** [comment]
My point was that I wanted it with remote from the beginning and I'm
working on it right now and need it for my own stuff soon so I plan on
sneaking it in :P we can do a 3.2 release for it if you want... Doesn't
really matter to me. But the feature is coming soon and I can't wait long
to have it in PyPi.

**Comment by adammhaile** [comment]
Fair enough.

**Comment by adammhaile** [comment]
This is in dev and will be in 3.2
