### ISSUE TITLE
External classes need to be specified in two places in a project.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#340]
If you want to use a class like https://github.com/rec/bp_midi/blob/master/bp_midi.py#L35-L64, you have to do this in two places:

    {
        "path": "//git/github.com/rec/bp_midi",
        "animation": {
            "typename": "bp_midi.WX7Animation",
            ...
    }

This will be particularly bad when there are a lot of animations in a project.

(More, there is no way to add a single specific class without bringing that entire project into your `PYTHONPATH` but this is a limitation in gitty which I would like to fix, though I need to learn more about import - I'm already a little deep into it but there are further subtleties.)

**Comment by rec** [comment]
The solution should look like this:

{
    "animation": {
        "typename": "//git/github.com/rec/bp_midi/bp_midi.WX7Animation",
        ...
}

**Comment by adammhaile** [comment]
I would change it to `//git/github.com/rec/bp_midi/bp_midi#WX7Animation
<http://github.com/rec/bp_midi/bp_midi.WX7Animation>`
Because bp_midi.WX7Animation could also be a valid repo URL. We have no way
of knowing that intent and if we just auto-split on a `.` then we might
fail on something valid.

To prove my point, this is a valid repo URL:
https://github.com/adammhaile/bp_midi.WX7Animation

**Comment by rec** [comment]
Details, details!  :-)  (Surprised github allows `.` as it didn't [used to even allow `_`](https://www.quora.com/Why-doesnt-GitHub-allow-underscores-or-spaces-in-repository-names).

Yes, that would have been a big oops.  So `.` is clearly a poorly-conceived separator.

Let's actually list the special characters we use.

    : / . 

Possible choices for separators are

    @ $ # % & + ?

Eliminated choices:

    ( ) [ ] { } - * , < > =

And we need to represent the following ideas:

* Alias expansion
* Separating a github URL from an import path

That's it!

For aliases, I was suggesting `@` (as in @lias) but `$` is very familiar from shells.

For URL separators, well, we're down to `? & # +`, each of which already has some sort of meaning in a general-case URL.  Let's eliminate `& +` because their meanings are misleading and we're down to `# ?`.

Logically, I think there's a slight edge in correspondence of meaning for `?` but it looks too stupid in the URL, so `#` wins by a knockout.

And also` $` for alias expansion over `@`, whatta you think?

**Comment by rec** [comment]
Hah, I realized that we don't even need `#`, just `/`.

Remember that neither Python files nor directories can have an unexpected `.` in them.

So we potentially get URLs like this:

`gp://github.com/john.smith/bp_midi.WX7Animation/my_animation.my_class`

And we can always unambiguously break this up at the last `/`.  Everything before that is the path;  everything after that is a Python path.

And this is also really nice because it gives us "good defaults" - like these

`gp://github.com/rec/bp_midi/WX7Animation` means `gp://github.com/rec/bp_midi/WX7Animation.WX7Animation`

and  

`gp://github.com/rec/bp_midi/` means ` gp://github.com/rec/bp_midi/bp_midi.bp_midi`

---

Why `gp://`?  It stands for "git python".  

I don't want to re-use `bp`, which I'm now seeing as the command line program.  

Of course, we'll accept `http://` and `https://` as input values, but I don't want to actually print our URLs with `https://` because they don't correspond to actual resources and will 404 if clicked on...

**Comment by rec** [comment]
This is done!
