### ISSUE TITLE
`bibliopixel` command line program should also be installed as `bp`.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#344]
Sick of typing it.  :-D  

And developers will be typing it a lot.  We should make things easy for them.

Also, `bp` doesn't seem to be any sort of *nix or Windows command line command.  We should take it!

**Comment by rec** [comment]
Gmail doesn't let you send tar.gz, so I attached the results to this issue!

[BiblioPixel-3.1.3.tar.gz](https://github.com/ManiacalLabs/BiblioPixel/files/1204963/BiblioPixel-3.1.3.tar.gz)

**Comment by rec** [comment]
Sigh - pull requests are their own issues so I could have attached it directly.  :-)  next time!

**Comment by adammhaile** [comment]
That's exactly the right thing to do :)
