### ISSUE TITLE
un-Pythonic weirdness in `bibliopixel.util.d`

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#35]
https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/util.py#L1-L18

You very rarely have to use `__dict__` in Python, and I can't even understand what this is supposed to do, but I'm about 98% sure that there is some way to do this in Python with a couple of lines of code with no `__` in them.  :-D

**Comment by adammhaile** [comment]
LOL... That's used in PixelWeb extensively. It makes all dictionary keys accessible as attributes.
myDict.hello instead of myDict['hello']

And yes, it's a total hack. I'm all ears if there's a more pythonic way to do this.

**Comment by adammhaile** [comment]
Fixed with pull request #40
