### ISSUE TITLE
The `"run"` section should be owned by containers, not each animation.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#356]
There are two very separate concepts in `"run"` that we're conflating.

One is a record attached to each animation individually, saying things like "how long it's going to go on for".  Another is data attached _to the entire project_ about things like the thread structure of the project itself - like the upcoming `"run_on_main_thread"` parameter coming in #355.

In the existing code, container animations usually overwrite most of their children's `"run"` sections.  That's a code smell - getting people to "fill out a form" and then throwing most of it away.  :-D

The top-level `"run"` section should stay basically unchanged.  However, run properties for children should be managed _by their containers_ and not by individual animations.

**Comment by adammhaile** [comment]
Not true... sequence allows children to control fps, runtime, and others...

**Comment by rec** [comment]
This is basically the case right now - the container will set values like fps, etc _if_ the children do not.
