### ISSUE TITLE
Project should respect driver pixel count

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#360]
If you don't specify `num` in `layout` it tries to use the project default. For a matrix that's 32 x 32. This is wrong if you *did* specify `num` in the driver. If you did, it should pass that to the layout for it to figure it out. For example, with matrix, if I specified 64 pixels, it will assume I have an 8x8 matrix. But if I don't specify that in `layout` the project code tries to pass it 32 x 32 because that's the project default. Project should check the driver num count if available (I'm fine with it only doing this when a single driver) and pass that number along to layout.

**Comment by rec** [comment]
I am closing this because `--dimension` does all of this, _and_ we do a better job on guessing pixel counts when not set.
