### ISSUE TITLE
Mega-meta-test script.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#364]
We need a script that runs all the following tests:

* unit tests
* bibliopixel demo
* bibliopixel run
* BiblioPixelAnimation tests

(probably the last one is just a smoke test like all_test.py)

**Comment by adammhaile** [comment]
On that note... we should create a new requirements.txt type file that
includes the necessary packages for ALL BPA animations. Which would help
with all this.

**Comment by rec** [comment]
Just as a note - it turns out that there aren't very many packages for BPA, and one of them, `pyaudio`, cannot be installed in Travis so is no good.

**Comment by rec** [comment]
Oh, this is done!  :-)
