### ISSUE TITLE
If you run a threaded project, it immediately terminates.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#370]
Figured this out by reading the code, and tested it.

**Comment by adammhaile** [comment]
Wait? What? I've run threaded animations and the remote... works fine.
Example?

**Comment by rec** [comment]
https://gist.github.com/rec/6aa3273a20b127891fda751720db2417

**Comment by rec** [comment]
The remote isn't a "threaded animation".  run.threaded is `False` - but the remote itself spawns off a thread.

**Comment by adammhaile** [comment]
Oh... haha. Yeah... fair enough. I've never run a single animation that's threaded. What I was thinking of was "threadedUpdate".
So... this is kinda an anti-pattern. 
If you call `bp run` it should *never* let it be threaded. Just change that value to false and emit a warning that says 'Animations cannot be threaded when called from `bibliopixel run`, will run non-threaded' or similar.
If you call it from your in-code project loader then it's fine.
Either way... I feel better now. Scared me for a second. Much more minimal issue that I excepted at first.
