### ISSUE TITLE
Drop Python 3.4 support.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#379]

**Comment by rec** [comment]
1. What about Ubuntu 14.04LTS, which has python 3.4?
2. What about MacOS?  (ANSWER:  you already have to install Python 3 yourself...)
3. What about Windows? (ANSWER: same)

I think we need simply instructions on how to install the newer version as part of `main` and call it a day.

**Comment by adammhaile** [comment]
1) Solution, upgrade to 16.04LTS or upgrade python on 14.04LTS... it's
nearly 4 years old.
2) no problem
3) Windows users should be on 3.6 now

Well... it shouldn't even install on 3.4. Just link out to instructions on
why and how to update Python.
