### ISSUE TITLE
Unreachable code in `led.py`

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#38]
[This code](https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/led.py#L346-L354) probably can't be reached - if width and height were zero a few lines above, a non-zero value is retrieved from the driver.

Also, the code [here](https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/led.py#L332-L338) doesn't deal with the case where exactly one of width or height is zero...

**Comment by adammhaile** [comment]
This is long since gone.
