### ISSUE TITLE
`seconds` field in `Runnable` needs work.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#381]
1. The number of steps is precalculated and assumes that calling `step()` , i.e. rendering a frame, will take no wall clock time whatsoever.

2. If `seconds` is set, `self.sleep_time` is 0 and neither `fps` nor `sleep_time` are set, you get a division by zero error.  But this is a perfectly reasonable request to make - "perform this animation full-out for S seconds and then stop".

In particular, this is blocking me fixing #364 properly...

**Comment by adammhaile** [comment]
Huh... never did see that before making the change myself :P Oops.
