### ISSUE TITLE
Lists of colors are not aliased 

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#390]
Having a `colors` param is very common. It's always a list of colors and should be automatically converted.

**Comment by adammhaile** [comment]
@rec I see how to add new handlers but this one's a little weird because it's a list of one that already exists. And I couldn't figure out how to just call out to those already registered for `color`, so that I can obviously have max code reuse. 

If you can point me in the right direction I'll add this to my pending PR as it would be very nice to have for SparkCon.

**Comment by rec** [comment]
Easy peasy. Back in 2 hours and can send a review.

**Comment by adammhaile** [comment]
Ok... cool. Keep separate from anything else as I will pull this one in for
SparkCon :)
