### ISSUE TITLE
Can't load code from gists.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#411]
Neither the [user-friendly URL](https://gist.github.com/rec/32bc9170cb565d40c08c6958cdf28e68) nor the [raw URL](https://gist.githubusercontent.com/rec/32bc9170cb565d40c08c6958cdf28e68/raw/192c21b8893873f304b8d5a95acedf199f7aef20/scroll.py) work.

**Comment by adammhaile** [comment]
Huh
... This is what I was trying when I reported that other loady bug.

**Comment by rec** [comment]
That problem was fixed - that was loading JSON _data_ from gists.  I think that still works.

Now that I see that there are other formats to gist URLs, I think that some gist JSON URLs might be broken too, but I'll fix all of it.
