### ISSUE TITLE
Serial devices should not propagate an exception for communications errors during normal operation.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#413]
Even if our program and hardware were perfect, we'd see occasional communications just from electrical noise.

During connection or configuration, communications errors should be fatal, but during normal operation, we should just report exceptions and not terminate the program.

**Comment by adammhaile** [comment]
Typically, if there's a comm error the device needs to be reset. Not
always, but often. So this may not be possible. But I'd be happy to be
proven wrong.

**Comment by rec** [comment]
Is there a way to programmatically reset an AllPixel?

We can't cause any harm by relentlessly retrying in software when a reset is needed, though... right?

**Comment by adammhaile** [comment]
It happens automatically when configuring the AllPixel but only if the
configuration changes. There's no simple "RESET" command that can be sent.
And you wouldn't want to. The EEPROM has a limited life and doing that all
the time would decrease that.
Also, the problem isn't the AllPixel ;) Is the linux serial stack and/or
power issues.
