### ISSUE TITLE
Better parsing of project files.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#421]
(I unfortunately need to fix this before I finish the generic control animation so I'm writing it up as an issue to make sure I understand it...)

"resolution" is the process that resolves aliases and then loads code using `loady`.

The resolution process is pretty clean but we _apply_ it in a lame way - on an _ad hoc_ basis during the construction of various objects.

We have `animation.Collection`s, soon we'll have `MultiDriver`s and `TeeDriver`s, each of which have fields that are also objects - recursively.

More, for the generic control animation I also need to be constructing _function_ objects from a parameter.

Before this explodes, we need a better way.

Resolution needs to be done _before_ any objects at all are constructed, as just an operation on the project dictionary!  This will put all the resolution parts in one Python file, not scattered across a bunch of classes that have sub-objects.

--

Here's the solution.

Each class contains a static variable indicating the fields that it has that need to be resolved.

In the first pass, we walk through the dictionary, perform the resolution process only enough to get the actual class at each point in the node, and then use that static variable to recurse into selected fields and resolve _those_.

This will be very much like the FIELD_TYPE fields we currently have - which I will also clean up to be completely specific to each class.

**Comment by rec** [comment]
Or another way to see it - there are _eight_ calls to resolve in [this file](https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/project/project.py) - there should be just one!

**Comment by adammhaile** [comment]
I like it. Except we will not be calling it TeeDriver. ParallelDriver or
something else, but Tee is *way* too obscure. We need something that a
normal person will look at and have some idea of what it does. The only
thing they might think TeeDriver is would be something golf related :P

**Comment by rec** [comment]
FIxing this won't result in a TeeDriver :-P or whatever - it will simply open the door to compound objects of all types, whether Layout, Driver or Animation.

**Comment by adammhaile** [comment]
Nothing will EVER result in TeeDriver cause it won't be called that :)
