### ISSUE TITLE
`Serial` driver doesn't have a start method

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#425]
This only seems to cause an exception when you run Serial drivers through `bp run`.

`Serial` has no `start()` method: https://github.com/ManiacalLabs/BiblioPixel/blob/dev/bibliopixel/drivers/serial/driver.py

But `Layout.start` calls `Driver.start`: https://github.com/ManiacalLabs/BiblioPixel/blob/dev/bibliopixel/layout/layout.py#L43-L45

Sort of confused here as to how this works and what's going on, so assigning this to you.

**Comment by adammhaile** [comment]
A) What's the exception? Stack trace or it didn't happen! You know better than that.
B) NONE of the drivers have a start() method in Master. In dev the only one that has it is SimPixel which clearly you added.
C) layout.start() is not called anywhere in master or dev. I have no idea what it is.

Assigning back to you because this is all your doing :)

**Comment by rec** [comment]
I skipped the stack trace - because it's useless:

    Traceback (most recent call last):
      File "/development/env/bp/bin/bp", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/development/BiblioPixel/scripts/bp", line 15, in <module>
        main.main()
      File "/development/BiblioPixel/bibliopixel/main/main.py", line 62, in main
        return run(args) or 0
      File "/development/BiblioPixel/bibliopixel/main/run.py", line 42, in run
        raise ValueError('Run aborted')
    ValueError: Run aborted

If I had a useful stack trace, I'd send it to you, but even turning on --verbose _and_ --fail_on_exception failed to do so. 

Indeed, this deserves its own bug.  :-)

However, yes, it's all my own doing so :-D I deserve this one!
