### ISSUE TITLE
`bp demo` command throws an exception.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#439]
Forgot about this.  I'm not even sure if it works - I don't test it in my day-to-day work.

Why have two ways of doing things? Each demo should be replaced by a project from projects.

Let me know if this is reasonable and I'll port the interesting parts and kill it.

**Comment by adammhaile** [comment]
No, we still need users to be able to see a demo easily.

**Comment by rec** [comment]
So right now, `bp demo` doesn't work.  :-o :-D As I predicted!

What I'm going to do is to throw away most of the code and make it a wrapper over `bp run`.

**Comment by rec** [comment]
[demo-error.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1340466/demo-error.txt)

**Comment by adammhaile** [comment]
Ah, yeah... as long as it can just call into those project files we included that's cool. However, note that those project files do not currently get installed or put in the dist archive. So that will need to be updated.

**Comment by rec** [comment]
Works now.
