### ISSUE TITLE
Delete the "path" section of projects.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#440]
With loady, we really don't need this - you can specify the filename of the code you want directly in your project, or you can just run with `PYTHONPATH=` before your line.

And Projects already have too many parts.

(Again, I just want a sign-off that we should do this or not...)

**Comment by adammhaile** [comment]
No. I like it. Leave it.

**Comment by rec** [comment]
Well, the issue is that right now, it's pretty badly broken.  I think I actually have a fix to it in client though.

What happens right now is that if you run a bunch of projects with different paths, it'll load all the paths in _at the very start_ and then all the projects get all the paths.

That means if different projects have conflicting symbols, you get the symbol from the _last_ project to be loaded with that symbol.  Which means that if you're the earlier project, you get the wrong symbol.

The other point is _definiteness_.  Right now, adding stuff to the `path` means you are opening the door to any random crap that happens to be on your file system.  It means that if you design on one machine and deploy to another, your chances of it working correctly are reduced.

The `--isolate` flag mitigates this to some extent.

Also, I find this a bit dodgy because all this stuff is hard to really test in unit tests, for obvious reasons.

I'll close it for now but I reserve the right to re-open it for V4.
