### ISSUE TITLE
Mario gif is not being installed when BPA is installed

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#441]
This is a BP bug because it causes my bp integration tests to fail.

The log shows the issue - `python setup.py install` in BPA doesn't install any of the files from the graphics directory.

[setup-error.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1340616/setup-error.txt)

---

Now, this is weird - I didn't feel like I refreshed BPA at all, just did a clean install at a certain point into a new virtualenv.   

Could my environment have changed?  I rebooted today for the first time in months, but I didn't feel like I changed anything!

Ongoing...

**Comment by rec** [comment]
(I hand-installed this file so I can continue with my other branches fine...)

**Comment by adammhaile** [comment]
This is actually a known issue with BPA. I need to tweak the default paths
in ImageAnim

**Comment by adammhaile** [comment]
It does work if BPA is installed wtih "stetup.py develop"

**Comment by rec** [comment]
RIGHT!

That's the difference!  I did `setup.py develop` before!!

**Comment by adammhaile** [comment]
:) Log it with BPA if you'd like. I'll fix it.
