### ISSUE TITLE
Reprocessing animations

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#444]
See this: https://imgur.com/oSkd4hc

This is an example of a whole category of animations: "animations that take an existing frame buffer and manipulate it."

Writing a base class for such animations, as well as a specific implementation of this effect - "bubble sort one element at a time" - would be quick and fun.

**Comment by adammhaile** [comment]
Holy crap, that's awesome. Yes please :)

**Comment by rec** [comment]
Probably more to come on this, but I have hit the issue at least.
