### ISSUE TITLE
Testing that we haven't broken the hardware is a pain.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#445]
We have a hardware rig coming up (detailed below), but we do not have enough manpower to have this thing run for each commit that is checked once there are more developers.

Certainly for version number change releases we should run it but what happens when we have an active dev or even feature branches?

This is a chore and who likes chores?

I'm filing this as an issue for the record, but we can just close it after discussion.

---

I propose an ongoing discipline that reduces workload in this area - call it "hermetic drivers".  It's probably easier to do than to explain, and I expect it to take almost no work.  :-D

The eventual goal is that, if all the tests pass, that we only have to run hardware tests _for changes to the drivers_ - files that are below `bibliopixel/drivers/`.

Of course, actual releases would need hardware testing, but with an active `dev` branch, releases would be a very small fraction of the number of commits within `dev`!

So we're aiming for
* all code or data in or below `drivers/` requires hardware to be completely tested.
* all code and data outside `drivers/` can be completely tested without hardware

---

In other words, _once_ we got into this state of "hermetic drivers", we would have very high confidence that code that didn't touch `drivers/` did not need to be tested on hardware, and could be pushed to dev with only unit and integration tests.

We are not in such a state.  There is code outside `drivers/` that could break code within it, and isn't protected by tests - conversely, there is code within `drivers`/ that doesn't need hardware to fully test it.

That's fine for now.  Nor do I propose a great effort to fix this - but simply as we go forward to move to keep `drivers/` for _exactly_ code that can only be fully tested with hardware and take everything else out.

For the moment, I'm just going to note at the top each review if it _does_ touch `drivers/` or dependent code and generally keep an eye out towards any moves either way that are logical.

---

Original correspondence below.

---

One thing that I need to finally go ahead and build is my Pi-based uber-testing rig. And send one to you :)
Plans for that is actually what the PiPixel came out of.... here's my plan:

- Have *at least* the following LED strips: APA102, SK9822, WS2812, WS2801, LPD8806 (there are [others](https://github.com/ManiacalLabs/AllPixel/wiki/Connecting-the-LEDs) but really no one uses them)
- Design and build a board that connects to the Pi along with the PiPixel (or probably just includes the same bits) which has MOSFETs for each output strip. The pi would be able to turn each on/off via the testing framework.
- Each strip would be connected to outputs from both the Pi itself and an AllPixel.
- The 3 possible outputs on the Pi (SPI, GPIO13, GPIO18) would be selectable from the Pi through the test framework.
- Testing framework would iterate through each strip on the test jig, enable its power MOSFET, then run some brief test pattern. This unfortunately cannot be 100% eyes-off because this would exist to visually verify that each strip shows the intended pattern. Obviously it would also catch some more egregious bugs where something actually crashes, which is great. But the intent would be to take a new build of BP and run it against this new hardware test and visually verify that each and every strip is shown properly via both the Pi and the AllPixel

Anyways, that's the plan. I also just need this for new versions of the AllPixel firmware or whatever. My testing process now is crazy manual and kind of annoying. Along with figuring out the doc stuff I'll design this jig shortly.

Point is... with something like that I'd be more comfortable with adding more people to the team.

**Comment by adammhaile** [comment]
+10 to this :)
