### ISSUE TITLE
More functions for the function animations

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#453]
We now have two planned types of "function" animations - animations like your math animation or my upcoming  reprocessing animations, animations which rely on selecting some mathematical formula or simple function to get interesting behavior.

People love this [stuff].  We should extract out the animation code into a separate file that's referred to using loady names, and then throw in several dozen more, and then we can say, "100 new waveforms" or something like that.

**Comment by adammhaile** [comment]
Not sure what you mean exactly...
Here's the mathfunc stuff, btw:
https://github.com/ManiacalLabs/BiblioPixelAnimations/blob/master/BiblioPixelAnimations/matrix/MathFunc.py

**Comment by rec** [comment]
Ah, great, thanks!

I'll clarify this once the reprocessing animation is in, so there's a clear example.
