### ISSUE TITLE
The whole "texture" idea is broken and should be separated from matrix.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#459]
We pay for this in complexity and it makes the semantics of `Matrix.set` entirely unclear.

In particular, we suddenly have this new variation of set:  `set(x, y, None)`.  We know that `None` pixels don't play nicely, and we decided not to use them.  

Here, `None` is a secret code for "black if there's no texture otherwise a pixel from the texture".  Trappy!

More, if you change the texture, you have no way to tell which pixels are from the texture, and which from the program material.

Instead, we should extract out this code into a Transform.  Black will no longer be anything special, just the default - but you should be able to specify any color or range of colors to be overwritten by the texture, so you can do Chromakey/green screen effects.  

Because the texture happens as a step after the color_list, if you change textures, key colors or switch off texturing entirely, it will be like it never happened...

**Comment by adammhaile** [comment]
As long as it's 4.0 and not 3.x that can absolutely go. I'm not really a
fan.

**Comment by rec** [comment]
It's likely that we can also do marvellous things with alpha channel maps... :-D

**Comment by rec** [comment]
And, as a "Transform" we can develop the new functionality in parallel with the old code.

So you'll be able to specify a "texture" as before, _or_ have a Transform that does the same thing.  Once we know the Transforms all work, we can deprecate the original functionality and start moving people to it while still maintaining complete backwards compatibility...
