### ISSUE TITLE
Dealing with package breakage - why didn't CI catch the loady issue?

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#465]
External dependencies are known to be evil.  But in any real project, the number of external dependencies tends to be monotonically increasing.

We have to assume that external package breakage is an issue that can only get worse if left alone.  How do we fix it?

Here's what happened the last time.

* I made a change to loady that worked for `BiblioPixel/dev` but not for `BiblioPixel/master`
* CI didn't warn me of anything
* A new installation of bp failed

I actually started writing this with one idea in mind, but now I think there's only one solution - we need to have _explicit version number ranges_ for all our packages in our dependencies.

This would have completely fixed the problem above.  `master` would continue to install the good version.  `dev` would have _required_ the new library, and also worked perfectly.

Right now, we have four main dependencies, and one of them isn't under our control (flask) and we have ten test dependencies, none of which are under our control (and test breakage is still breakage, even if it only affects developers).

The fact that these dependencies are "reliable" doesn't make them 100%, and even though both of us are very resistant to adding new dependencies, it is a matter of certainty that two years from today, `dependencies.txt` will contain more entries.

An explicit version number range completely prevents random breakage.  It makes for a highly reproducible environment.  Every few months, we update to the newest versions, test all the dependencies, and push the new dependencies.

**Comment by adammhaile** [comment]
+100. It sucks that version pinning has to be a thing, but it's the right
thing to do.
