### ISSUE TITLE
Check the rebase of dev.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#489]
I prepared a new branch called [x-dev](https://github.com/rec/BiblioPixel/commits/x-dev) on my fork which is a rebase of dev over the new master.

Two lists of commits since a common ancestor are attached.  The line counts show that as expected the new branch has two more commits than the old: the version commit and the pixel_width commit.

Mark this as fixed, and then I'll force-push x-dev over dev.

[dev.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1499522/dev.txt)
[x-dev.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1499523/x-dev.txt)

**Comment by rec** [comment]
Actually - hold off on this.  I'm going to have to push in those remaining changes for pixel_width, which I haven't written yet.

**Comment by rec** [comment]
Alright, here's the improved version of x-dev with the three new changes incorporated. 

[dev.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1501947/dev.txt)
[x-dev.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1501948/x-dev.txt)

One list has five more commits than the other, as expected.

You probably don't even have to read these, I'm pretty sure I did my due diligence.

**Comment by adammhaile** [comment]
Looks good to me.

**Comment by rec** [comment]
I rebased and pushed dev.

**Comment by adammhaile** [comment]
Sweet
