### ISSUE TITLE
"single class" configuration of user animation types.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#494]
People want to write a little code.  There needs to be a good "one file" mechanism for them to do that - so they only have to prepare one .py file and go.

This came up trying to explain to Harold on the user's list how to make a project.  I concluded that in his case it was more time that it was worth...!

I have a plan for this...

**Comment by rec** [comment]
In specific, you should be able to just type:

    bp strip1.py

and "have it all work".

**Comment by adammhaile** [comment]
Looks like you've done this :)
