### ISSUE TITLE
Full documentation of project sections

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#516]
* .py projects
* project defaults
* "aliases" section
  * Link to better documentation of aliases here
* "dimensions" section
* "per animation" project setting

**Comment by rec** [comment]
Hold off;  tweak coming.

**Comment by rec** [comment]
We also need:

    "options"
        "numbers"
        "threaded"
        "path"

    "controls"

**Comment by adammhaile** [comment]
Also need details on the options for every driver and layout!
