### ISSUE TITLE
Channel Order issue

### ISSUE THREAD

**Issue by KrauseS10** [ManiacalLabs/BiblioPixel#52]
Hello,

I am following the instructions on [https://github.com/ManiacalLabs/BiblioPixel/wiki/Display-Setup#channel-order](url) and I am having an issue correcting the color order.  I am getting 1 Blue, 2 Red, and 3 Green, 1 black, and the 3 rotating colors.  I believe i followed your instructions to set the channel order in driver_base.py (adopting for what I am guessing is just a newer code structure) to the result of this:
`def __init__(self, num=0, width=0, height=0, c_order=ChannelOrder.BRG, gamma=None):`
But even after rebooting the pi the results of the LEDStrip.py script still shows 1 Blue, 2 Red, 3 Green, etc.  I am not sure how to fix this, any input would be welcomed.

Also In this scenario I am using a LPD8806 LED strip.

**Comment by adammhaile** [comment]
You shouldn't be using driver_base directly, ever. If you are using the
LPD8806 directly on the SPI port of the Pi use DriverLPD8806. If using the
AllPixel, use DriverSerial.
Can you please send the actual code you are using?
You should first try the test pattern with ChannelOrder.RGB as using it
with any other ChannelOrder initially defeats the process, then note the
colors. If you get 1 Blue, 2 Red, 3 Green, then you need to use
ChannelOrder.BRG like you have.
Please send your test code and more details on your current hookup.

**Comment by KrauseS10** [comment]
From the wording on the channel-order page i thought that was the file to edit.  here is my bibliopixel/drivers/LPD8806.py file currently.
`from spi_driver_base import DriverSPIBase, ChannelOrder


class DriverLPD8806(DriverSPIBase):
    """Main driver for LPD8806 based LED strips on devices like the Raspberry Pi and BeagleBone"""

    def __init__(self, num, c_order=ChannelOrder.BRG, use_py_spi=True, dev="/dev/spidev0.0", SPISpeed=2):
        super(DriverLPD8806, self).__init__(num, c_order=c_order,
                                            use_py_spi=use_py_spi, dev=dev, SPISpeed=SPISpeed)

        # Color calculations from
        # http://learn.adafruit.com/light-painting-with-raspberry-pi
        self.gamma = [0x80 | int(
            pow(float(i) / 255.0, 2.5) * 127.0 + 0.5) for i in range(256)]

        # LPD8806 requires latch bytes at the end
        self._latchBytes = (self.numLEDs + 31) / 32
        for i in range(0, self._latchBytes):
            self._buf.append(0)

    # LPD8806 requires gamma correction and only supports 7-bits per channel
    # running each value through gamma will fix all of this.
    # def _fixData(self, data):
    #    for a, b in enumerate(self.c_order):
    #        self._buf[a:self.numLEDs*3:3] = [self.gamma[v] for v in data[b::3]]

MANIFEST = [
    {
        "id": "LPD8806",
        "class": DriverLPD8806,
        "type": "driver",
        "display": "LPD8806 (SPI Native)",
        "desc": "Interface with LPD8806 strips over a native SPI port (Pi, BeagleBone, etc.)",
        "params": [{
                "id": "num",
                "label": "# Pixels",
                "type": "int",
                "default": 1,
                "min": 1,
                "help": "Total pixels in display."
        }, {
            "id": "c_order",
            "label": "Channel Order",
            "type": "combo",
            "options": {
                    0: "RGB",
                    1: "RBG",
                    2: "GRB",
                    3: "GBR",
                    4: "BRG",
                    5: "BGR"
            },
            "options_map": [
                [0, 1, 2],
                [0, 2, 1],
                [1, 0, 2],
                [1, 2, 0],
                [2, 0, 1],
                [2, 1, 0]
            ],
            "default": 0
        }, {
            "id": "dev",
            "label": "SPI Device Path",
            "type": "str",
            "default": "/dev/spidev0.0",
        }, {
            "id": "SPISpeed",
            "label": "SPI Speed (MHz)",
            "type": "int",
            "default": 2,
            "min": 1,
            "max": 24,
            "group": "Advanced"
        }, {
            "id": "use_py_spi",
            "label": "Use PySPI",
            "type": "bool",
            "default": True,
            "group": "Advanced"
        }]
    }
]`

Even setting c_order=ChannelOrder.BRG does not change the way they light up.  It is still 1 Blue, 2 Red, 3 Green.

also for completeness sake here is my LEDStrip.py script:
`from bibliopixel.led import *
from bibliopixel.animation import StripChannelTest
from bibliopixel.drivers.LPD8806 import *

#create driver for a 12 pixels
driver = DriverLPD8806(12)
led = LEDStrip(driver)

anim = StripChannelTest(led)
anim.run()`

Once again input is welcomed.

**Comment by adammhaile** [comment]
Whoa... you never have to edit *any* file BiblioPixel! Ever.
Just do this in your script:

driver = DriverLPD8806(12, c_order = ChannelOrder.RGB)

Try the strip test with that. Then change c_order once you see the colors
it outputs using RGB.

**Comment by KrauseS10** [comment]
I completely misinterpreted that wiki page!  Everything is good now and it is showing the right colors... Thank you very much!

**Comment by adammhaile** [comment]
Awesome :)

**Comment by rec** [comment]
Without reopening it, I'd say this is a classic misunderstanding between
"hobbyist" and "geek".

You quite reasonably are expecting to tinker with all the parts to get
results.  We on the other hand see our code as a packaged component, one
that is never changed, so we're surprised when you change it!


I think we can avoid this surprise in future with a little documentation,
and even better, a tiny "sample project" that we expect people to copy and
then modify.


On Wed, Jun 15, 2016 at 10:48 AM, adammhaile <notifications@github.com>
wrote:

> Closed #52 <https://github.com/ManiacalLabs/BiblioPixel/issues/52>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ManiacalLabs/BiblioPixel/issues/52#event-693350235>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAPdsmp-lEOTd6PfDCFofGNwVXooFwW6ks5qMBDQgaJpZM4I18Da>
> .
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000
