### ISSUE TITLE
Uninstalling `BiblioPixel` doesn't uninstall `bp`.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#540]

**Comment by rec** [comment]
I felt I did this reliably before, but I just tried it twice and couldn't reproduce it.

**Comment by adammhaile** [comment]
I've never had that work. I feel like I saw a reason why it does that
somewhere, but can't find it now.
There is this though: https://github.com/pypa/setuptools/issues/175
