### ISSUE TITLE
Get rid of context managers!

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#56]
Tiny tweak, but my reading of all the `__enter__` and `__exit__` is that they aren't doing anything and more, could be implemented as an external class if needed.

https://eev.ee/blog/2016/07/31/python-faq-why-should-i-use-python-3/

**Comment by rec** [comment]
@adammhaile - OK, there is some actual code in there in a couple of places.

The whole `_exit` vs `__exit__` can go - if client code wants the same effect, they can override `__exit__` and call `super().__exit()`.  

Do you ever use this?  Can I see a use case to work with?

**Comment by adammhaile** [comment]
The only major use is animation.py: https://github.com/ManiacalLabs/BiblioPixel/blob/dev/bibliopixel/animation.py#L60
Still trying to understand why and how they aren't needed.

**Comment by rec** [comment]
But you never _use_ these as context managers!

You'd have to have a `with` statement - that's the only possibility.  Otherwise, those functions are not called!

**Comment by adammhaile** [comment]
Oh... yes I do. In my own scripts and in PixelWeb. They are to be used by
users of the animations.

**Comment by rec** [comment]
PixelWeb! let me look there.

This is super-low-priority btw.  I was just curious... :-)

**Comment by adammhaile** [comment]
Even if I'm remembering wrong and it's not in pixelweb, I use it other
places. For example with some of my games. The context handler disconnects
the serial link to the gamepad on exit.

**Comment by rec** [comment]
> The context handler disconnects the serial link to the gamepad on exit.

Why not use the destructor?  :-)

But sure, it seems a reasonable strategy - I just want to isolate exactly how you use it so I can understand it.

**Comment by rec** [comment]
Actually, I think this is a timewaster.  :-D  Unless you're committed to tweaking this, I'm going to hold off on doing anything.

**Comment by adammhaile** [comment]
<shrug> I like the with statement?

**Comment by rec** [comment]
I didn't remove any actual context managers!

I added an `__enter__` that should be needed, and cleaned up that `_exit`.
