### ISSUE TITLE
Remove user aliases and the `bp alias` command.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#564]
The reason is that we have much better ways to do this now - you can use a project default, _or_ you can use the `"alias"` section in your project.

There's nothing the `bp alias` command offers that these don't, and it's quite a lot of stuff there making it work.

I can write something that reads any existing .bibliopixel_alias files that are around and imports them into your defaults file.  On the other hand, I'd honestly be shocked if anyone were using this unannounced feature (though it is documented).

**Comment by rec** [comment]
Thoughts?

**Comment by adammhaile** [comment]
Kill it. I definitely don't use it.
