### ISSUE TITLE
SPI Setup page has no mention of python-periphery

### ISSUE THREAD

**Issue by haooken** [ManiacalLabs/BiblioPixel#574]
> Unable to create drivers
> Error with dev: /dev/spidev0.0, spi_speed: 24 -
> Unable to import periphery. Please install:
>     pip install python-periphery
> 
> Please see
>     https://github.com/maniacallabs/bibliopixel/wiki/SPI-Setup
> 
> for details.

Probably just a matter of updating the docs. I was trying to get some APA102s to run with the PIPixel, and saw the above error. Installing python-periphery resolved the problem and now I have blinkenlights, but I noticed that the Wiki page mentioned has no reference to python-periphery. Also that page was last updated March 23 as of this writing.

**Comment by rec** [comment]
Assigned to Adam, who knows more about this.
