### ISSUE TITLE
add --spi option

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#577]
In prep for better testing... We have --ledtype that can override that option for both Serial and SPI from the CLI, but having a --spi option would be nice so we could test FILE, PYDEV, and PERIPHERY with the same test json

**Comment by adammhaile** [comment]
@rec - You have better idea how the --ledtype thing works than I do :P You'll need to at least point me in the right direction.

**Comment by rec** [comment]
Fair enuf!  I'm a little hazy on FILE, PYDEV and PERIPHERY but :-D I learn fast.

This won't happen until I have the universal test board, right?  (We need a good name for that!)

**Comment by adammhaile** [comment]
It should literally just be a replacement like is done with --ledtype now.
Right now I think you are just inserting "ledtype" into any driver instance
if provided.
--spi would just insert an "interface" option (maybe it should be
--interface instead) into the drive.
