### ISSUE TITLE
"BiblioPixel troubleshooting" document

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#586]
Generally, there are only a tiny number of possible things that have gone wrong in the past.

We should create a one-page troubleshooting document that tells people things like:

1. If there's an ERROR, and there isn't a clear explanation of how to fix the problem, it's probably our fault - report it to the mailing list
2. If there's no ERROR, then they probably got the wires wrong.
3. These sorts of hardware need to run as sudo (see also #582)
4. Here's the mailing list.

I believe at this point that we make fairly clear explanations of ERRORs resulting from the user making a mistake - bad JSON files, unknown colors like Bluck or Bloo, negative times and that sort of thing.  If the error messages aren't clear, people should be reporting them to us anyway so we can clear them up.

**Comment by rec** [comment]
I'm pasting in #561 and closing it:

--

This is from my notes over the last few days, and I wanted to store them, to be put in a troubleshooting page or FAQ.

"serial.serialutil.SerialException: write failed: [Errno 5] Input/output error"
One cause for this is if your LED lights aren't powered (in my case, the power supply had become unplugged). You might see the lights work until many of them are lit up - and then crash when the processor can no longer output enough power.

We might also catch this specific error and annotate it with a suggestion when we print it (we do quite a lot of that).

SyntaxError: invalid syntax during installation of BP..
This is a normal part of the Jinja installation and can be ignored. (I knew this, both others might not.)

I'll add more here as these show up and we can eventually move this to publicly-visible documentation.

 adammhaile commented on 20 Dec 2017
Regarding #1: What's actually happening there is you are USB powering and
when you start, it draws more than 500mA and the poly fuse on the AllPixel
trips. Fortunately it's a poly fuse, so it resets after removing power. But
I wanted to be specific about the reason.

**Comment by adammhaile** [comment]
+1
