### ISSUE TITLE
SPI Setup diagram bug

### ISSUE THREAD

**Issue by SloMusti** [ManiacalLabs/BiblioPixel#60]
The image on SPI Setup page: https://github.com/ManiacalLabs/BiblioPixel/wiki/img/RPi_LEDStrip_bb.png contains an error in text below LED strip, text should read Pin 23 (SCLK) -> CI (Clock), currently is says Pin 21. Correct pin is shown on the image itself.

**Comment by rec** [comment]
We still have this issue!  @adammhaile ?

**Comment by adammhaile** [comment]
Will fix it when I get back in town (visiting family at the moment).

**Comment by adammhaile** [comment]
fixed
