### ISSUE TITLE
Deploy documentation onto readthedocs

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#604]
https://readthedocs.org/projects/bibliopixel/

**Comment by rec** [comment]
So what needs to happen for this to go off??  I'm eager to get all the docs into one place.

**Comment by rec** [comment]
PING!  :-D

I would like to at least have partial documentation up, perhaps with warning and a link on the front page to the "production" Wiki.

I want to start writing .rst documents and then sending links to them to the user's list, and I have no way to do that if there isn't a build of RST files to some web place going on!

**Comment by adammhaile** [comment]
I'm out of town with no computer... Will have to wait until at least this
weekend.
