### ISSUE TITLE
Animations should not be allowed to be `None`

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#624]
This is a classic antipattern!  In particular, I keep running into code that doesn't check if `self.current_animation` is `None`...

We use `None` to represent "no animation" - when there's a failure loading an animation for a slot.  We should instead have an animation named `NoAnimation`  - so no special cases again!

**Comment by adammhaile** [comment]
That will break the remote. It depends on the details in the REST call to
show a null value for an animation that didn't load so it knows to show
that button greyed out.

**Comment by rec** [comment]
A fix - e.g. replacing `if not animation:` with `if getattr(animation, 'empty', False):` would take like 23.57 seconds.

Also - what happens when you want to e.g. report on the display _why_ you can't load that animation?  There's no way to put any more information into a `None`!  :-D

Basically, `None` breaks type and so it's a constant source of exceptions in production code.  Using a collection is so much easier if you know all the elements have the same type!

Modern C++ and Java are very quickly moving towards `std::optional` and `Optional` respectively, for exactly the reasons above.  

`None` is still very useful in Python, but finding it as a value in your collection is like finding a frog in your glass of milk... 

How much code out there does stuff like this:

    value = d.get('foo')
    if value is None:
        # ...

instead of the more correct:

    none = ()
    value = d.get('foo', none)
    if value is none:
        # ...

https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions
https://www.lucidchart.com/techblog/2015/08/31/the-worst-mistake-of-computer-science/

**Comment by rec** [comment]
Bad news. :-(

Functionality which relies on animations being possibly `None` has been broken for a quite a while... there is no current codepath where any entry into `Collection.animations` can ever be `None`!

:-(

There was no unit test for this functionality, and no integration test, and so it got vanished at some point in the proceedings.

Developing...
