### ISSUE TITLE
`Remote` animation no longer handles broken animations gracefully.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#626]
It used to replace those animations by `None` and then continue on, but in the current codebase there is no way for a subanimation to be `None`.

Remote _with_ a bad element needs to be part of the whole test suite!  As it is, I never test the error case.

**Comment by rec** [comment]
I think I fixed this but I can't run the remote animations any more.

**Comment by adammhaile** [comment]
I'll take a look.
Really gotta figure out why you can't run remote on your Mac though...
that's no bueno :(
