### ISSUE TITLE
Regularizing the description of LED drivers in projects.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#631]
There's that ugliness with LEDtype that we have previously discussed.  Now we completely control the construction process, we can make all that invisible without changing our actual code that creates drivers.

This would be a tiny amount of code in the pre-creation phase.  We would of course continue to be perfectly backwards compatible...

Here are examples of projects with this new format - just slightly tweaked from before.  (The whole driver/drivers thing already works fine in the current codebase, but I wanted to show the uniformity of the format now...)

    # AllPixel
    {
        "driver": "lpd8806"
    }

    # AllPixel, different c_order
    {
        "driver": {
            "typename": "lpd8806",
            "c_order": "grb"
        }
    }

    # SPI, different c_order
    {
        "driver": {
            "typename": "lpd8806",
            "c_order": "grb",
            "spi": true
        }
    }

    # AllPixel, different c_order, multiple device_ids
    {
        "drivers": [
            {
                "typename": "lpd8806",
                "c_order": "grb",
                {"device_id": 10}
            },
            {
                "typename": "lpd8806",
                "c_order": "grb",
                {"device_id": 20}
            },
            {
                "typename": "lpd8806",
                "c_order": "grb",
                {"device_id": 30}
            }
        ],
    }

    # Same as before, using driver as a default for drivers
    {
        "driver": {
            "typename": "lpd8806",
            "c_order": "grb"
        },

        "drivers": [
            {"device_id": 10},
            {"device_id": 20},
            {"device_id": 30}
        ]
    }

**Comment by adammhaile** [comment]
lgtm
