### ISSUE TITLE
Linear flow for documentation.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#640]
One of the things I like about the Python documentation (and many other bodies of documentation) is that there are always "previous/next" buttons at the top of each page, and you can basically go through all the documentation by using them.

"Studies have shown" (though the ones I saw might have been private) that people remember can use documents much better that way and will often prefer to click "backward" ten times than hunt for a hyperlink because it is less cognitive baggage.  I am certainly one of those people.

We have on the wiki now such a linear flow, but I don't think the new documentation has it.

**Comment by adammhaile** [comment]
@rec This is automatic if you keep adding to the Contents in index.md, we just only have one doc right now. But the contents will show up on the left pane, and you'll have a next/previous topic at the bottom. It's ReadTheDocs standard.
