### ISSUE TITLE
Clean up the `"run"`/`Runner` section.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#642]
There are issues with "run", most of which can't be cleaned up until 5.0!  :-)

1. It contains `"amt"` which isn't really meaningful (#641)

2. Some of it is only applicable to the top-most animation:  `"main"` and `"threaded"`.  (Some subanimations _need_ their own threads, some need not to have threads, but they _all_ ignore the `"threaded"` parameter and do what they need to do.

3. The interactions between the other parts isn't clear - what happens if you e.g. set `seconds` and `max_steps`, or `sleep_time` and `fps`?

4. The `Runner` and `Animation` have to know about each other to work together, which poses issues for the whole project/construction thing.  Behind the scenes I fix it in a really simple way - I do surgery so the runner is just a constructor parameter to the animation. 

5. The name in the project is `"run"` but the variable in the animation is `runner`.  

---

Issues 4 and 5 have negative implications for controllers.  Right now, if you looked at a project and then wanted to have, say, a button to change FPS, you'd _expect_ to use an address like `"run.fps = 30"` but the _actual_ address is `"animation.runner.fps = 30"`.

My suggestion for what we can for 4.0 is this:

1. Fix #641.

2. Move `"main"` and `"threaded"` to the top, and create a new `"options"` section to put them and a couple more random parameters into.

3. Fix 3 with a little documentation

4. Deprecate `"run"` parallel to the animation in favor of `"run"` as a parameter to the animation.  Note that this already works today - you can put `"run"` in either position - I'm proposing just changing the documentation.

5. Rename `BaseAnimation.runner` to `.run`.  Note that this conflicts with an existing "public" method on `BaseAnimation`, but not one that I think anyone should really be calling, so I think we should rename it as `_run` or something else entirely.

**Comment by rec** [comment]
Ah, and I should reinforce - we can do this all and be backwards compatible with 3.x projects.

**Comment by adammhaile** [comment]
You are the Runner king... I'll defer to you on this @rec.
