### ISSUE TITLE
Document "the S rule" and use it everywhere.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#646]
For `"drivers"` and `"controls"` and for `"animations"` in a collection, we have what I'm calling "the S rule":

1. A project section that ends in "s" is a list of things.  An example is "drivers"
2. If you specify "driver", you mean a list with just that driver, so `"driver": {...}` means the same as `"drivers": [{...}]`
3. If you specify "drivers", it's a list of drivers
4. If you specify "driver" _and_ "drivers", then the dictionary "driver" is used as a default for each driver in "drivers".
5. The Python path is the same as the name - so it should be "bibliopixel.driver"

It's actually really natural if you see examples - it's harder to explain than to show.

There are three slight problems with the rule now.  The first is that the directory is today "drivers/" not "driver/" - see #644 - and we have special purpose code to fix that.  The second is that we don't do rule 4 for animations.  The third is that we don't have a single place that does these rules.

I thought there was some other place we had a plural too but perhaps I was wrong.

We should clean up the code a little so the rule is true, and then document it somewhat more clearly than the above.

**Comment by adammhaile** [comment]
+1
