### ISSUE TITLE
No bibliopixel.led module installed

### ISSUE THREAD

**Issue by Citiroller** [ManiacalLabs/BiblioPixel#655]
[https://github.com/ManiacalLabs/BiblioPixel/wiki/Display-Setup#channel-order](Your example code) for a Strip Setup doesn't work.
First of all it hast to be
`from bibliopixel.drivers.SPI.LPD8806 import *`
instead of
`from bibliopixel.drivers.LPD8806 import *` This will fail with the same reason as No 2.
Secondly theres no led.py with the installed files (I searched my whole filesystem), so
`from bibliopixel.led import *` is impossible with the error ImportError: No module named 'bibliopixel.led'

Am I missing something obvious here? The installation went fine, because i can import bibliopixel.animation for example.

**Comment by Citiroller** [comment]
Ok, so this is just an issue on your documentation. Would be nice if you update it so no one gets confused. I have to use bibliopixel.layout instead of bibliopixel.led

**Comment by adammhaile** [comment]
@Citiroller - Right you are. And I've fixed that doc page. What was there was for BiblioPixel 2, not the latest v3.x
Thanks for pointing that out!

**Comment by jerbmann** [comment]
Is it me, or am I still not seeing this update in the docs? I am trying to get things running and am wondering if I'm missing anything else that the wiki has wrong. I can get the Strip test to "run" but it is not behaving as the docs say it should. I see 1 red, 2 blue, then a green, a pink, a yellow, and one that flashes from green/yellow/orange. Is this expected?

**Comment by adammhaile** [comment]
Can you link to the doc page you are talking about? Pretty sure we caught them all. Could be wrong though.
What you are seeing sounds like something is wrong with your LED strip. What type are you using?

**Comment by jerbmann** [comment]
I literally just refreshed the page and the update is there now. I still have it open in its old state and can see it without the update. No worries, as long as its up to date now.

The strip I'm using is this one - https://www.adafruit.com/product/306 - a 5m strip, powered with a 10a power supply.

**Comment by adammhaile** [comment]
Decrease the SPI data rate to 1Mhz and see what happens (spi_speed=1).

**Comment by jerbmann** [comment]
leds:
1: red
2: blue
3: blue (with a little bit of green on that i can see)
4: cyan
5: purple/cyan ish
6: purple
7: flashes between green and off at a very slow rate.

**Comment by adammhaile** [comment]
out of curiosity, set c_order="RBG"
How old is the strip?  And what are you running this on? A raspberry pi?

**Comment by jerbmann** [comment]
I had c_order="BGR" before based on documentation, changing it to RGB and now I have
1: green
2: red
3: pink
4: blue/purpleish that flashes to blue sometimes
5: purple
6: orange
7: flashing green/yellow/red/off/orange ...
it feels like my data feed or clock is all messed up. changing the spi speed to 2 and i get completely different results. 4, 5, and 6 all change colors on the 3rd or 4th blink of 7 at speed 2.

Raspberry Pi 3 model B v1.2 fresh raspbian install with nothing else
Strip is brand spanking new

**Comment by adammhaile** [comment]
Oh... BGR is most common for LPD8806. But your result there means you
probably have a GRB order. They aren't all the same.
Are you using a level shifter?

**Comment by jerbmann** [comment]
No level shifter. I do have it wired like this - https://learn.adafruit.com/light-painting-with-raspberry-pi/hardware

Which has the pi getting its power from the same power supply through the gpio, but I see the documentation here - https://github.com/ManiacalLabs/BiblioPixel/wiki/SPI-Setup - it's not powered that way.

**Comment by adammhaile** [comment]
Your data/clock wires are likely too long or too low gauge. You're
definitely getting some interference.
Send me a pic of the hookup.
Shameless plug but I do recommend something with proper power routing and
level shifting:
https://www.tindie.com/products/ManiacalLabs/pipixel-raspberry-pi-led-strip-hat/

**Comment by jerbmann** [comment]
Definitely soldered.

**Comment by adammhaile** [comment]
Fair... I had to check ;)

**Comment by jerbmann** [comment]
Ugh, it's worse. 
1: green
2: blue
3: pink
4: cyan
5: flashing green/off
no other leds lit. This is a wiring issue apparently.

**Comment by adammhaile** [comment]
That would be my assessment as well. Sorry. Try not powering the pi and
LEDs from same supply.

**Comment by jerbmann** [comment]
Snipped the 5v connection to gpio and powering off micro usb = same results as above.

**Comment by adammhaile** [comment]
You either need better wires, are connected to the wrong pins, or need a
level shifter.

**Comment by jerbmann** [comment]
I'll try those in that order. The pins I'm fairly certain are correct, as changing those gives me zero feedback from the leds. That's as far as I can take it right now. Thanks for all your help and feedback. I'll keep playing - will report back later this weekend when I find a fix (knock on wood).
