### ISSUE TITLE
Failure to load an animation with Remote is a hard fail

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#663]
It used to be that if running remote and an animation failed to load, it would just skip it and grey out the animation button. Now it just hard fails. Tested when trying to run this project file: https://github.com/adammhaile/BiblioPixelProjects/blob/master/SparkCon2017/1K.json
Failed on ImageAnim because pillow was not installed.

**Comment by rec** [comment]
Can you try this again on your hardware?  I believe it has gotten past those errors (due to a previous fix) and should all work now but I can't see it to the end w/o the hardware.
