### ISSUE TITLE
The `LEDTYPE` called `GENERIC` can't actually be used in a driver.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#665]
[`GENERIC` is `0`](https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/drivers/ledtype.py#L5) but the constructor of the driver [disallows `0`](https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/drivers/serial/driver.py#L24-L25)

Either code needs to be changed or there needs to be documentation as to why this is so!

**Comment by adammhaile** [comment]
@rec - ledtype, not num! This is the correct line of code:
https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/drivers/serial/driver.py#L21
And I use GENERIC all the time.

**Comment by rec** [comment]
Oops.  :-D
