### ISSUE TITLE
opencv-python is a pretty huge dependency...

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#671]
It takes almost as much time to install as everything else put together and we don't use it for any core operations.  Perhaps it should be optional?

**Comment by adammhaile** [comment]
It's an optional dependency of BPA and in no way required by BP. The only place it's even referenced is in test_requirements.txt and you added it there so you could load all of BPA as a smoke test: https://github.com/ManiacalLabs/BiblioPixel/commit/43330a4ee844608c4d40f5fd0caa2dfe4e97e83a

**Comment by rec** [comment]
Hah, right!  Dammit.  

I just created a small "load everything as a developer" script and it was fairly slow on this fast laptop - I'll bet it'd be three times as slow on a RPi.  So I was looking for ways to get a quick improvement with little work.

Well, I'm going to assign this to me and 50/50 do nothing and close it later.  :-)
