### ISSUE TITLE
No way to detect current port number for remote.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#691]

**Comment by rec** [comment]
"There might be a firewall."  :-)

**Comment by rec** [comment]
I changed this bug.  It is possible to set the port in the project, but seemingly no way to retrieve that value from within BP, which I need for another bug... :-)

**Comment by rec** [comment]
Bleh.  Clearly I need my eyes checked.  :-D

**Comment by adammhaile** [comment]
huh....wut?
