### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by MarkSwanson** [ManiacalLabs/BiblioPixel#7]
I was having trouble getting SPI0 to work as well. A number of blogs/howtos mentioned /dev/spi0*.
I could never get this to work. I was always seeing /dev/spi1*.

Your instructions were the first ones I came across that actually explained that you would never see /dev/spi0* and would always see /dev/spi1* - and the way to determine which SPI was activated and mapped to /dev/spi1* was by parsing /sys/kernel/debug/pinctrl/44e10800.pinmux/pingroups.

Now I can continue my little hobby project.
Thank you!

**Comment by adammhaile** [comment]
Welcome! Glad we could help! That was certainly a problem for us at first too... it seems they changed to spi1 at some point. Had to compile our instructions from about 10 different places :)
