### ISSUE TITLE
midi and keyboard controls probably don't stop when `stop()` is called

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#725]
`stop()` just sets a flag and that flag isn't being checked in either of those.

(We shut down fine because everything's a daemon.)

**Comment by estiens** [comment]
Can confirm this is still an issue (maybe fixed in v 4.0?)

When using the MIDI controller, I have to use ye olde
`kill -9 $(ps aux | grep bibliopixel | awk '{print $2}')`

to actually kill the program. CNTL-C will stop running the animation, but the program itself never exits

**Comment by rec** [comment]
4.0 is just a gleam in our eye :-D but it might be fixed in the next release, which will be this upcoming week.

I am a little slack and close issues when the fix is committed, not when they're pushed to release.  :-)

`bp` actually keeps track of its own PID, so you can do `bp restart` (`SIGHUP` or `kill -1`) and `bp shutdown` (`SIGTERM` or `kill  -15`) from another command line somewhere.

As of this instant, there is no `bp kill` (`SIGKILL` or `kill -9`) but I just sent out a [tiny pull request](https://github.com/ManiacalLabs/BiblioPixel/pull/834) to add `bp kill`.  Even if we have fixed this specific bug, I'm sure we'll run into other hanging bugs at some point, particularly if people write their own code...
