### ISSUE TITLE
Sphinx build crashes

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#739]
That last commit: https://github.com/ManiacalLabs/BiblioPixel/commits/docs

The first line that triggers this is the first link line _but_ I have pasted that line in a simpler .md file and it didn't crash.

[sphinx-err-w670cvpq.log](https://github.com/ManiacalLabs/BiblioPixel/files/1881463/sphinx-err-w670cvpq.log)

**Comment by adammhaile** [comment]
Can you link me to the line in this commit? https://github.com/ManiacalLabs/BiblioPixel/commit/b388dfbd77e6d3828352c75b94726faa847c67a2

**Comment by rec** [comment]
This line:

https://github.com/ManiacalLabs/BiblioPixel/commit/b388dfbd77e6d3828352c75b94726faa847c67a2#diff-5db2c860d4e7e5ef74eb7cfc33d99f8eR33

**Comment by adammhaile** [comment]
Uhh... I have no idea. Personally, we should have no sub-directories in the
doc files. It just mucks things up too much.
