### ISSUE TITLE
New type `ip_address`

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#785]
We already use this in several places and do somewhat different parsing in both.

We should handle:

1. a string representing a DNS name
2. a string representing a dotted four-part address
3. a list of four numbers

We should report if the numbers in a dotted address are out of range [0..255].

**Comment by rec** [comment]
Also, it should probably default to `"localhost"` or `127.0.0.1` - not sure which is better.

**Comment by adammhaile** [comment]
127.0.0.1 is better as it involves no lookup.
Python already has an IP address class:
https://docs.python.org/3/library/ipaddress.html
Though it doesn't do DNS. Maybe a small wrapper class that takes anything
and does some sanity checking on the value would be nice.
