### ISSUE TITLE
Running without `fps` or the equivalent can get poor results

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#792]
I've noted this before.

For example, if you have a control sending data to an empty animation, if you don't set an fps and the processor runs flat out, the updates to simpixel are extremely intermittent.

**Comment by adammhaile** [comment]
Personally I think we should have a default capped FPS, like 60 at the
most. Honestly, anything above that is just silly. I usually even just run
at 30fps as it looks smooth but doesn't put too much strain on the CPU.
