### ISSUE TITLE
Better handling of DMX offsets

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#795]
DMX is 1-based - BP is 0-based. 

Our current model is confusing, because we use an offset - that requires an extra +1 which confuses users.  If the lighting designer "sets their board to channel 100", then the offset is -99...

We could easily flip the sign.  But if we tweaked the code to fix this, we'd get the other unintuitive result that offset=0 actually moved everything 1 channel...

The solution involves adding a little functionality, which results in clearer names:

* channel_start (default 1)
* channel_end (default 512)
* pixel_offset (default 0)

This gives us a little extra functionality in specifying exactly the channels we want _and_ it's extremely clear how it works, and how offsets work, and how they interact with channels

I toyed with:

* step (default 1, can be a list)
* scale

but well... not entirely clear how those would work and not worth the extra effort

**Comment by adammhaile** [comment]
Sounds good to me, even if DMX is *wrong*. 0-index for life :)

**Comment by rec** [comment]
MIDI's the same way!

Any protocol for non-computer scientists starts at zero.  Your regular person just doesn't start counting at zero.  :-D

**Comment by adammhaile** [comment]
Heathens... without zero, we have nothing :P
