### ISSUE TITLE
Just loading drivers.network_receiver changes your `sys.path`

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#796]
https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/drivers/network_receiver.py#L11

Not very neighborly!

My theory is that this is unnecessary, but I don't know why it's there. @adammhaile, any clarification?

**Comment by adammhaile** [comment]
Holdover from before we knew better and fixed the module layout:
https://github.com/ManiacalLabs/BiblioPixel/commit/587719e392c963bfb715de8f0f0f53c7b47b475d
