### ISSUE TITLE
n leds per pixel

### ISSUE THREAD

**Issue by fluesternBlock** [ManiacalLabs/BiblioPixel#8]
Hi!

I created a led matrix with 2 leds per pixel. How could I create an instance of the LedMatrix class with this requirements? I think it isn't possible with the coordMap and I have to program a new inheritance of your LEDMatrix class. Is this correct?

Thanks!

**Comment by adammhaile** [comment]
Are each of the two LEDs for each "pixel" individually controllable or do
both always show the same thing? if it's the latter, than they are
logically one pixel, not two. There should be no need to make a new LED
class. Why do you have 2 leds per pixel? Do you have a picture or diagram?
What chipset are you using?

**Comment by fluesternBlock** [comment]
My led strip has two LEDs per segment. Each led is controllable. Chipset is LPD 8806. i am using also raspberry pi.

**Comment by adammhaile** [comment]
Oh... yeah. That's how the LPD8806 always is. Count each LED as a pixel,
not each controller chip. If you use DriverLDP8806 (I assume you are using
direct SPI from a Pi or BeagleBone) it will work fine. Shouldn't even need
to provide coordMap. Just if your LED layout is serpentine or not.

**Comment by fluesternBlock** [comment]
Yes, I using direkt SPI from my Pi.
That isn't what I want to do.  I want to combine two LEDs (one controller chip) to one pixel. I think this isn't possible with the class LedMatrix. I need to write a new class for this requirement. Right?

I build a matrix with 100 segments (each segment includes one controller chip). The matrix consists of 200 LEDs. The height of my matrix is 10 rows and the width of my matrix is 10 columns.

**Comment by adammhaile** [comment]
Got it... that makes more sense.
I would just say write your animations to be aware of the 2 pixels = 1
pixel layout, but that wouldn't let you use existing animations.
I suggest making a new class that inherits from LEDMatrix and then override
set(), setRGB() and setHSV() with something like this:

```python
#I'm assuming your matrix is laid out with the strips going horizontal.
    def set(self, x, y, color):
    #each X coord is actually 2 pixels on the same row
    #x=0 is actually x=0 & x=1, x=1 is x=2 & x=3, etc.
    x1 = x*2
    x2 = x1+1

        if x1 >= self.width or x1 < 0 or y >= self.height or y < 0:
            return #just throw out anything out of bounds
        else:
        pixel = self.matrix_map[y][x1]
        self._set_base(pixel, color)

    if x2 >= self.width or x2 < 0 or y >= self.height or y < 0:
            return #just throw out anything out of bounds
        else:
        pixel = self.matrix_map[y][x2]
        self._set_base(pixel, color)
```

Do basically the same thing for setRGB and setHSV (for consistency and
compatibility with animations that use them.
You technically should also override the get() methods.

That's not tested, but it *should* work.

**Comment by fluesternBlock** [comment]
I thought so, that I need to write a new class. I was not sure.

Thanks for your help.

**Comment by adammhaile** [comment]
No problem. Glad I could get you on track :)
