### ISSUE TITLE
Properly curated "projects" section.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#828]
The projects section is currently a hodge-podge.

It includes:

* Huge test projects that exhaustively test a lot of animations
* Tiny projects used for internal testing of features
* Random crap that shouldn't even be there.
* And a [near-random numbering-naming system](https://github.com/ManiacalLabs/BiblioPixel/tree/master/projects) that obscures more than it enlightens

We should divide this into "testing/experimental" (and hide that away) - and a set of carefully curated and documented projects that demonstrate each aspect of BLiPS without too much cruft which we make heavy use of in the documentation.

**Comment by adammhaile** [comment]
Good thing we are moving to YAML and can now use comments in project files
;)
I'm out of town again... will fixup my PR soon.

**Comment by MyNameIsCosmo** [comment]
This would pair well with the documentation.
Project files should relate to documentation examples.
I.E. **Matrix Layout with Parallel Animations**, **Project Driver Configuration**

I have a couple "test" projects for use with the [Raspberry Pi RGB LED Matrix](https://github.com/MyNameIsCosmo/BiblioPixel/blob/driver_rpi-rgb-matrix/bibliopixel/drivers/PiRGBMatrix.py) that I plan to include in a future PR along with the driver.
