### ISSUE TITLE
APA102 Multiple types of LED-arrangement on a contiguous range of pixels

### ISSUE THREAD

**Issue by gaitskell** [ManiacalLabs/BiblioPixel#83]
Is there a way to declare multiple LED arrangements for a single contiguous range of APA102 pixels.

For instance: LED Pixels
 0-299 could be a 1st LED strip
300-555 could be a 16x16 LED square matrix 
556-855 could be a 2nd LED strip
etc

Is there a way to accommodate this in the current device declaration scheme? Or can this be added?

**Comment by rec** [comment]
Oops, sorry I didn't answer here!

I'm hard at work in the other window (so to speak) on a bigger solution to this.  However, it's going to take some weeks at least - the current system assumes that there's a 1:1 correspondence between drivers, animations and LEDs.

Thanks for bringing this up, it was really useful in my thinking on this!  I'll be sure to keep you updated.

I'm on this about 1/3 time right now, and I'm pretty productive at this sort of thing, so it will get done fairly soon.

**Comment by adammhaile** [comment]
@rec - Didn't we add this?
