### ISSUE TITLE
Auto parse .yaml and .yml

### ISSUE THREAD

**Issue by estiens** [ManiacalLabs/BiblioPixel#833]
Looks like you are autoparsing files with a .yml extension as YAML, however YAML themselves seem to like `.yaml` See: [http://yaml.org/faq.html](http://yaml.org/faq.html)

This is a pretty easy fix to make, I think even I can handle it as a non-python programmer :)
https://github.com/ManiacalLabs/BiblioPixel/blob/1255ecd3c9bc91dcafecff493e152934e0e24c87/bibliopixel/util/json.py#L19

Better would maybe be to allow a flag to force a type of file encoding

**Comment by rec** [comment]
We are actually moving to parsing _everything_ with the Yaml parser, so all of this will be moot in a very short time!  (There's a pull request in flight as we speak...)

Stay tuned.  :-D
