### ISSUE TITLE
BiblioPixel Development Scripts are Installed with Pip by Default

### ISSUE THREAD

**Issue by MyNameIsCosmo** [ManiacalLabs/BiblioPixel#839]
When BiblioPixel is installed (from source or via Pip), it will install the `bibliopixel` site-package along with `scripts`.
On top of installing 2 packages, this has the potential to clash with any other package writing to `scripts`, at least on my machine.

```
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/bibliopixel
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/bp
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/developer_install
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/make_bp_help_documentation
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/make_documentation
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/make_documentation_live
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/new_version
/home/user/Werk/bibliopixel/.env/lib/python3.5/site-packages/scripts/send_artnet
```

This was mentioned in #799 
I will be branching off #799 and rebasing then pushing some fixes to setup.py for this issue.

Future releases should have development scripts installed if a developer flag is set.

**Comment by rec** [comment]
Ah, this is an outright bug.  Good catch!

I actually have no understanding of how this part of the install goes, but those scripts should not be installed.  They are only for developers, and should never appear in your PATH.

Only `bp` and `bibliopixel` should get installed.  Yes, there could still be a conflict but at some point that's unavoidable.

**Comment by rec** [comment]
Actually, I don't even think `bibliopixel` should be installed.

**Comment by adammhaile** [comment]
No, `bibliopixel` still needs to be callable. At least until 4.0 where we
are allow to make breaking changes.

**Comment by MyNameIsCosmo** [comment]
I'll set up another PR later today with a proposed fix for this issue.
