### ISSUE TITLE
Improve Entrypoint Scripts

### ISSUE THREAD

**Issue by MyNameIsCosmo** [ManiacalLabs/BiblioPixel#840]
BiblioPixel currently uses `scripts/bp` as the CLI entrypoint.
Python supports the use of `bibliopixel/__main__.py` as an entrypoint (along with any other function within the package).

This also gives the benefit of being able to run `python -m bibliopixel` from the base directory to test any development code without having to run *setup.py*.

The benefit to moving `scripts/bp` into `bibliopixel/__main__.py` would be mainly cleanup, but also to address part of #839.

PR #799 has moved `scripts/bp` to `bibliopixel/__main__.py`, but needs to be cherry-picked.

`Setup.py` is pretty powerful, and you can define multiple entrypoints to your package.
```python
setup_kwargs = {
    ...
    'entry_points': {
        'console_scripts': ['bibliopixel = bibliopixel.__main__:main', 'bp = bibliopixel.__main__:main']
    },
    ...
}
```

**Comment by rec** [comment]
> This also gives the benefit of being able to run python -m bibliopixel from the base directory to test any development code without having to run setup.py.

That's interesting - how does this work?

Right now, if I want to do development on BLiPS or any other package I have, I go to that project and type

    python setup.py develop

and then links to the code in that project are put into my virtualenv.

Now I can run anything I like within that virtualenv, and it all uses the code I'm editing in that project.  I can also do that for other packages it depends on, like `loady` and `BiblioPixelAnimations`.

How would I duplicate that functionality after the proposed change?






There are other advantages, too - for example, if I type `cat \`which bp\`` I can immediately
