### ISSUE TITLE
When `bp` dies with `kill -9`, it leaves a PID file behind

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#845]
This is a known issue.  I knew it was going to do that when I wrote it!

Fixing this isn't trivial.  I did not want to catch SIGKILL because if we do that, and something is wrong in the cleanup, you end up with a process you can't kill.

The "best" way would be to run `bp` as a daemon subprocess and have the controlling master process actually handle deleting the PID - but my attempts to write a Python daemon for another project I'm on found a huge amount of information indicating that the standard library for this, python-daemon, has a lot of issues.

Another way would be to update the PID file periodically, and then ignore "stale" PID files.  That's probably what we should do.

**Comment by adammhaile** [comment]
Windows doesn't have PID files. So this is a non-starter as far as I am
concerned.

I feel like this guy every time I have to say such things...
[image: image.png]
But we gotta keep things cross-platform. All this process signal stuff
never really sat well with me because of it. But sadly I've found no
Windows equivalent.

**Comment by rec** [comment]
"[image: image.png]"?  :-D

We need the functionality provided by signals.  There will be some sort of way to make that work on Windows, even if we need to listen to a port to do it!

I was thinking about how this really should go in the long-term, and a master `bp` should basically be running "all the time" during your `bp` sessions, as a daemon.  Then we'd always just talk to that master daemon, and there would be no difference between Windows and other platforms.

Unfortunately, I've been trying to build a Python daemon for another project, and the existing code for this is subject to a lot of issues... :-/  

So this is "long-term"...

**Comment by rec** [comment]
Actually, the program pretty brutally overwrites the PID file and keeps going with only a warning.  So this isn't really an issue.  We don't actually stop you from having two instances of `bp` running either.  The PID is just a convenience that lets you restart or kill _the most recent invocation_ of `bp`.

So I'm closing this.
