### ISSUE TITLE
Writing data files is broken.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#857]
"Yaml" is on my reading list and I saw some articles recently...

I was investigating the fact that using `yaml.load(` allows arbitrary code execution and I discovered that YAML is bad at serializing anything that isn't an exact type it knows...

In JSON, if I serialize a class that's derived from `dict`, like `collections.OrderedDict` or `.util.PersistentDict`, it happily treats it like a `dict` and serializes it.

In YAML, it serializes it as a bogus object reference - one that can't be loaded with `load_safe`.  If I try to serialize with `yaml.dump_safe(` I get an error.

Worse, if I unserialize the `.util.PersistentDict`, and then copy it into the existing `PersistentDict`, this gives me two of these in memory at the same time pointing to the same file!  Who knows which gets to write last?

Fixing #838 might fix this.

Here's an article that has the problem and some other good complaints too: https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html

**Comment by adammhaile** [comment]
What error do you get with dump_safe? I use that all the time.

**Comment by rec** [comment]
Have you ever tried using dump_safe on something that isn't just strings, dicts, numbers and lists?  :-)

We now have this issue with the new PYYAML so we really should fix it.  :-D

**Comment by rec** [comment]
Fixed with the other yaml change.
