### ISSUE TITLE
Keep leds on after project ends

### ISSUE THREAD

**Issue by dannyvanderzande** [ManiacalLabs/BiblioPixel#862]
Is there a way that I can keep my leds on in the state they were when the project file has reached the end?

I'd like to use this to turn on a one color strip around my room by sending the bp run command over ssh for it to turn on and another one later for it to turn off. If I leave the first command run the program indefinitely I can't just kill it because it will be running in the background.

Can anyone help me out here? Thanks

**Comment by adammhaile** [comment]
No, you can't. Not all LEDs will stay on unless they are actively updated and some can start going crazy from errant RF interference.  So, we actively turn off the display upon completion.
But what you want to do is easy enough another way... use the remote:

```
{
    "driver": {
        "typename": "simpixel",
        "num": 50
    },
    "layout": {
        "typename": "strip"
    },
    "animation": {
        "typename": "remote",
        "external_access": true,
        "port": 5000,
        "title": "Test Remote",
        "default": null,
        "animations": [
            {
                "animation": {
                    "typename": "BiblioPixelAnimations.strip.ColorFill.ColorFill",
                    "name": "Red",
                    "color": "#ff0000"
                },
                "run": {
                    "fps": 5
                }
            },
            {
                "animation": {
                    "typename": "BiblioPixelAnimations.strip.ColorFill.ColorFill",
                    "name": "Blue",
                    "color": "#0000ff"
                },
                "run": {
                    "fps": 5
                }
            }
        ]
    }
}
```

Run that and then browse to http://simpixel.io and http://localhost:5000
You'll get a remote control with 3 buttons; STOP, Red, and Blue

This just uses the ColorFill animation which actively updates the strip. My example does it 5 times per second, but you could set that to 1 fps and it'd be fine. 

If you want to automate that somehow, you can just do a GET request to http://localhost:5000/run_animation/Red - or whatever animation name you want to call. Note, animation names cannot have spaces.
wget, curl, python requests, etc. will all handle that fine.

**Comment by dannyvanderzande** [comment]
I had been messing around with the remote but couldn't figure out how to

**Comment by adammhaile** [comment]
Yeah.... the docs are in the process of a complete rewrite. We were pretty far behind on a bunch of stuff that's been mostly internal stuff that wasn't quite ready for primetime yet. But the remote works quite well.
