### ISSUE TITLE
`cleanup` needs to move to Project

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#893]
Trying to debug #892, I got distracted into finally figuring out how "cleanup" works, so I wanted to document it.

The clean up of drivers is accomplished as follows:

* `animation.cleanup()` gets called
* if the animation is the top-level animation, then `layout.cleanup()` gets called
* `layout.cleanup()` calls `driver.cleanup()` for each driver.

All of this can go. My plan is to call all the cleanup from the top.

---

I also want to distinguish between "cleaning up resources" and "clearing the screen after execution".

Right now, layout.cleanup() does both.  But these are basically unrelated functions.

**Comment by rec** [comment]
Ah, there are some animations that have legit cleanups, but no layouts do.  I can still delete most of the code.

**Comment by adammhaile** [comment]
Yeah, animations absolutely need that. But I think the layout stuff was
speculative.
