### ISSUE TITLE
Repeated running of simpixel sometimes results in that port being permanently in use

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#894]
If I do a lot of starting and stopping, I eventually run into this issue. 

No other `bp` instances appear to be running, but I get this error:

    Cached server 1337 on your machine is already in use.
    Perhaps BiblioPixel is already running on your machine?

Even extreme measures like `killall bp` and `killall python` have no effect on this state.  Various forms of `ps` show nothing interesting, but `netstat -anb` does - the relevant parts are pasted below.

Eventually I have to reboot.

Any ideas?  This is beyond me...

    Active Internet connections (including servers)
    Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)        rxbytes    txbytes
    tcp4     542      0  127.0.0.1.1337         127.0.0.1.51406        CLOSE_WAIT         646          0
    tcp4       0      0  127.0.0.1.51406        127.0.0.1.1337         FIN_WAIT_2           0        320
    tcp4     542      0  127.0.0.1.1337         127.0.0.1.51404        CLOSE_WAIT         646          0
    tcp4       0      0  127.0.0.1.51404        127.0.0.1.1337         FIN_WAIT_2           0        320
    tcp4     542      0  127.0.0.1.1337         127.0.0.1.51402        CLOSE_WAIT         646          0
    tcp4       0      0  127.0.0.1.51402        127.0.0.1.1337         FIN_WAIT_2           0        320
    tcp4       0      0  192.168.178.95.51389   192.30.253.125.443     ESTABLISHED       1220       3341
    tcp4     542      0  127.0.0.1.1337         127.0.0.1.51367        CLOSE_WAIT         646          0
    tcp4       0      0  127.0.0.1.51367        127.0.0.1.1337         FIN_WAIT_2           0        440
    tcp4     542      0  127.0.0.1.1337         127.0.0.1.51365        CLOSE_WAIT         646          0
    tcp4       0      0  127.0.0.1.51365        127.0.0.1.1337         FIN_WAIT_2           0        440
    tcp4       0      0  *.1337                 *.*                    LISTEN               0          0

**Comment by adammhaile** [comment]
That's pretty much a known thing with *nix systems. I've never found a way around it. If you don't give it time to cleanup it will eventually be unrecoverable.

One thing you could try is this:
`sudo lsof -t -i tcp:1337 | xargs kill -9`

or on regular linux (above for OS X)

`sudo fuser -k 1337/tcp`

**Comment by rec** [comment]
All right!

I'm going to leave this open still until I get it into the documentation.

**Comment by rec** [comment]
I can make it happen pretty well every time by running the release_tests and interrupting it during the MIDI test.

It's something to do with running bp as a subprocess.  I'll look into this further, it's sort of annoying when testing.
