### ISSUE TITLE
Test LED-Matrix-Animation doen't work fine

### ISSUE THREAD

**Issue by fluesternBlock** [ManiacalLabs/BiblioPixel#9]
It's me again.
I have tried your example of the Wiki for the LED matrix.
Here is my code:
MatrixTest.py:
from bibliopixel.animation import BaseMatrixAnim
import colors

class MatrixTest(BaseMatrixAnim):
    def __init__(self, led, start=0, end=-1):
        #The base class MUST be initialized by calling super like this
        super(MatrixTest, self).__init__(led, start, end)
        #Create a color array to use in the animation
        self._colors = [colors.Red, colors.Orange, colors.Yellow, colors.Green, colors.Blue, colors.Indigo]
    def step(self, amt = 1):
        #Fill the strip, with each sucessive color 
        for i in range(self._led.numLEDs):
		#drawRect(self, x, y, w, h, color):
            self._led.drawRect(-1, -1, i+1, i+1, self._colors[(self._step + i) % len(self._colors)])
        #Increment the internal step by the given amount
        self._step += amt

animTest.py:
from bibliopixel.drivers.driver_base import ChannelOrder
from bibliopixel.drivers.LPD8806 import DriverLPD8806
from MatrixTest import MatrixTest

from bibliopixel.led import *
import time

driver = DriverLPD8806(200, ChannelOrder.BRG, True)
led = LEDMatrix(driver, 20, 10, rotation = MatrixRotation.ROTATE_0, vert_flip = False, serpentine = False)

anim = MatrixTest(led)

anim.run()

The matrix shows time to time the expected result and then anything else. It is a kind of magic ;-)

While I just formulate this question and my matrix is set to completely blue (all 200 LEDs). Suddenly, there are 8 pixels shown as white. But I don't know why. I didn't do anything. I set the whole matrix with the following coding to blue:

from bibliopixel.drivers.driver_base import ChannelOrder
from bibliopixel.drivers.LPD8806 import DriverLPD8806

driver = DriverLPD8806(200, ChannelOrder.BRG, True)

from bibliopixel.led import *
import time

led = LEDMatrix(driver, 20, 10, rotation = MatrixRotation.ROTATE_0, vert_flip = False, serpentine = False)

led.fillRect(0, 0, 20, 10, (0,0,255))

Have you any idea?

Thanks for your help!

edit: I have a feeling that my Raspberry Pi is getting slower. Have you any idea why this might be.

**Comment by adammhaile** [comment]
Oh... yeah, LPD8806 is REALLY bad about picking up electrical noise. My porch lights (which are LDP8806) go nuts every time I turn a ceiling fan on :P 

Try:

DriverLPD8806(200, ChannelOrder.BRG, True, SPISpeed = 2)

It defaults to 16MHz which is problematic for some setups. I've found that 2MHz usually avoids most issues. Also, some LPD8806 strips just can't handle more than 8-12MHz (usually because they are poorly made).

But 2MHz should be more than fast enough for what you need.

**Comment by fluesternBlock** [comment]
It works! Thanks! 
I have further problems with my pi. My pi time to time it becomes so slow. Sometimes the pi crashes. But only that pi for the led Matrix. I don't know why. Have you any idea?

**Comment by adammhaile** [comment]
Did you overclock it? Sounds like a stability issue. Also make sure you are
running the latest Raspbian. How old is the Pi?

**Comment by fluesternBlock** [comment]
I didn't overclock it. The pi is one year old. The raspbian is up to date. I think that the SD card is defect.  It's my second SD card for it. After i used the New one, the pi was fast. The pi with the current SD card is sometimes faster and will be slower.

**Comment by fluesternBlock** [comment]
I wrote some animations in the past with your library. Thanks again. Great work.

I have the same problem as described again. I don't know why. Last week, all my animations work fine. This week (nothing changed) in dependent of the color some other pixels are drawed in different color. If my matrix is off few seconds later some pixels are on.
The simplest invocation of led.fillScreen() doesn't fill the whole matrix. Two lines not filled.If I call led.drawLine() fill these two lines correct.

Have you an idea what to do?

**Comment by adammhaile** [comment]
Can you take a picture of your setup and connections? you've definitely got some sort of heardware issue?

**Comment by fluesternBlock** [comment]
I found the bug. I found a cold soldered joint. I hope this is the right word in english. 
It works fine, now.
Thanks!

**Comment by adammhaile** [comment]
That's the right term. Glad it works now :)
