### ISSUE TITLE
Avoid adding functionality through flags;  remove `--gif` flag

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#902]
I have put too much functionality in the flags section, with the result that run.py is complex and hard to understand.

A great deal of the functionality could have been accomplished with defaults files - `-d=my-default.yml` in the current notation, `my-defaults.yml+my-project.yml` in the new notation.

The recent `--gif` flag is a very good example of something that shouldn't have been written that way.

I'm probably going to choose not to document those and instead show the default file way to do things every time.

**Comment by rec** [comment]
Here's a list of flags we should be removing, because they are better done with defaults files:

    -a ANIMATION, --animation ANIMATION
    -b BRIGHTNESS, --brightness BRIGHTNESS
    -d [DEFAULTS [DEFAULTS ...]], --defaults [DEFAULTS [DEFAULTS ...]]
    --dimensions DIMENSIONS, --dim DIMENSIONS
    --shape SHAPE
    -g [GIF], --gif [GIF]
    -l LAYOUT, --layout LAYOUT
    --numbers
    -p PATH, --path PATH
    --simpixel SIMPIXEL   Run SimPixel at a specific URL
    -t LEDTYPE, --ledtype LEDTYPE

(I'm putting `-d`/`--defaults` in there because it's better done with the `+` operator.

**Comment by adammhaile** [comment]
Wait, I thought you wanted to get rid of the defaults files?
Hard no to this. I use these a LOT. Defaults are only good if you do *one
thing* on that system. I run a million different things on the same system
and love being able to change those on the fly.

**Comment by rec** [comment]
No, I want to get rid of _user_ default files - files that are stored in your home directory and that are mixed into every project.

I also want to get rid of the concept of "defaults" altogether - instead, you just write:

   bp strips.yml+project.yml

instead of `bp project.yml -d=strips.yml`

And then we don't have to talk about "defaults" at all.

Putting together projects from small files is the way to go.  Right now our --help is unreadable because of all these endless flags.  None of that code has any unit tests covering it, either.

I want there to be a lot less for the average person to learn.  Having pages of flags and then saying, "You don't really need to know these" is still daunting.

If there are two ways to do things, I want to eliminate one of them.  Too much needless choice is bad.

If I have to penalize you, perhaps the only user who makes use of this, in order to make the program more approachable, I will definitely do that.

---

But I'll bet we don't!  Let's see your actual workflow and I'll show you how we can do better.

I am working right now on "workflow" - explaining to someone who has never used this how to develop using the system - and I'm hyped to do this.

**Comment by adammhaile** [comment]
I'm fine with this change. But I still don't want to have to edit a file to
change a setting.

> I work fast, I need to be able to change things from the command line. Not
talking about files... I just want the --set option I mentioned :P
