### ISSUE TITLE
End support for Python 3.4 

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#908]
Now we support 3.7, we should contemplate when to end support for 3.4 - not immediately of course.  

The big advantage I see is type annotations in 3.5.

Note that 3.8.0 final is due in 14 months: [Sunday, 2019-10-20 (https://www.python.org/dev/peps/pep-0569/).   I'd like to obsolete 3.4 before we start to support 3.8!

---

It seems to me that the users have to install Python themselves on Windows and Mac/OS so it's not an issue there.

The problematic cases are:

* Ubuntu 14.04 LTS (Trust) which comes with 3.4 installed - end of life is April 2019.
* Ubuntu 16.04 LTS (Xenial) which comes with 3.5 installed
* Raspbian

Now, isn't it the case that recent Raspbians come with 3.5?

If so, then we can and should drop support in April 2019...

**Comment by adammhaile** [comment]
I'm pretty sure Raspbian has come with 3.5 for a while.
Yeah... let's drop it same time as Ubuntu 14.04
