### ISSUE TITLE
Error reports after project has closed down.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#910]
A project of mine with three drivers regularly spews out pages of errors when I shut it down with Control-C:
    
    DEBUG - animation_threading - Animation complete
    INFO - driver - Closing connection to: /dev/cu.usbmodem39
    INFO - driver - Closing connection to: /dev/cu.usbmodem23451
    INFO - driver - Closing connection to: /dev/cu.usbmodem38
    DEBUG - project - Project <bibliopixel.project.project.Project object at 0x1073370b8> finishes run()
    INFO - run - Received signal SIGINT
    ERROR - driver - Serial exception Attempting to use a port that is not open in write
    ERROR - io - Serial exception Attempting to use a port that is not open in read
    ERROR - devices - There was an unknown error communicating with the device.
    ERROR - driver - Serial exception Attempting to use a port that is not open in write
    ERROR - io - Serial exception Attempting to use a port that is not open in read
    [... 30 more lines omitted ...]

**Comment by adammhaile** [comment]
Never seen that before. Mac thing maybe?
