### ISSUE TITLE
Modification to 'bp -help' output

### ISSUE THREAD

**Issue by haooken** [ManiacalLabs/BiblioPixel#925]
In /bibliopixel/main/commands.py, please change the example

`bp color "indian red 4"`

to something that is less open to incorrect interpretation from a Political Correctness standpoint...

**Comment by rec** [comment]
"Indian Red" has nothing to do with native Americans! 

[Indian red is a pigment composed of naturally occurring iron oxides that is widely used in India.](https://en.wikipedia.org/wiki/Indian_red_\(color\))

I didn't make these colors up - I got them from a list of standard color names.  While I am extremely careful about not offending people, I believe this is fine...

**Comment by rec** [comment]
Now I've had coffee - you're complaining about the example, not the code!

Probably can't hurt to change the example.  Moment pls.
