### ISSUE TITLE
mkdocs (in the docs branch) handles subdirectories badly

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#965]
The file `doc/tutorial/1-Installing-BLiPS.md` becomes `doc/tutorial/1-Installing-BLiPS/index.html` but then links to that file are changed to be `doc/tutorial/1-Installing-BLiPS/` which will in many cases resolve to a directory list with a single file in it.

Why does it create a directory for each page with just a single file in each?

If we can't fix that, is there some .htaccess we could at least drop in the very top level of BiblioPixel so that the links work properly when previewing them locally?

**Comment by rec** [comment]
The only way to view this is with the live viewer - so I'm closing this.

**Comment by adammhaile** [comment]
What do you mean they don't work locally? Is that using the mkdocs server?
I honestly don't know what the solution is there.

**Comment by rec** [comment]
Using the mkdocs server works perfectly well.  I was just opening the files directly in Chrome...

**Comment by adammhaile** [comment]
Don't do that. It's not "valid" for mkdocs without those files being pushed
to a server. The problem is that you aren't viewing them from a proper web
server. Just use the mkdocs server.
