### ISSUE TITLE
"Failed to deploy" Travis error on current release on Python 3.5 only.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#973]
Seems to be some sort of authentication error on ManiacalLabs' account, but why not for 3.4 or 3.6?

https://travis-ci.org/ManiacalLabs/BiblioPixel/jobs/429249446

removing 'BiblioPixel-3.4.19' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading BiblioPixel-3.4.19.tar.gz
  5%|▌         | 96.0k/1.84M [00:00<00:02, 876kB/s]100%|██████████| 1.84M/1.84M [00:00<00:00, 4.61MB/s]
HTTPError: 400 Client Error: User 'ManiacalLabs' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/
PyPI upload failed.
failed to deploy

**Comment by adammhaile** [comment]
It only deploys from 3.5... I'll look into it.
